import face_recognition
import cv2
from imageio import volread
import numpy as np
# import def_load as load
import random as rn
import time

Start = time.time()

import face_recognition
import cv2
import numpy as np
from scipy.misc import face
act_face = 0

def img(where):
    global total_faces
    global act_face
    act_face = act_face + 1
    print("picture loaded ", where, "\t\t\t\t", act_face, "of", total_faces)
    image = face_recognition.load_image_file(where)
    # print(image)
    
    face_encoding = face_recognition.face_encodings(image)
    if str(face_encoding) == "[]":
        print("NO FINDABLE FACES!!!")
    # face_encoding = face_encoding[0]
    # print(face_encoding)

    return face_encoding [0]

def time_convert(sec):
    mins = sec // 60
    sec = sec % 60
    hours = mins // 60
    mins = mins % 60
    print("Time Lapsed = {0}:{1}:{2}".format(int(hours),int(mins),sec))

# This is a demo of running face recognition on live video from your webcam. It's a little more complicated than the
# other example, but it includes some basic performance tweaks to make things run a lot faster:
#   1. Process each video frame at 1/4 resolution (though still display it at full resolution)
#   2. Only detect faces in every other frame of video.

# PLEASE NOTE: This example requires OpenCV (the `cv2` library) to be installed only to read from your webcam.
# OpenCV is *not* required to use the face_recognition library. It's only required if you want to run this
# specific demo. If you have trouble installing it, try any of the other demos that don't require it instead.

# Get a reference to webcam #0 (the default one)
print("GO!")

# Load a sample picture and learn how to recognize it.
total_faces = 1023
camera = 1
video_capture = cv2.VideoCapture(camera, cv2.CAP_DSHOW)
time.sleep(1)
video_capture.release()



total_faces = 1036
act_face = 0

total_faces = 1037
act_face = 0






























 
AbrahamovaTv = img("faces/AbrahamovaTv.jpg")
Adamikova2AjRuD = img("faces/Adamikova2AjRuD.jpg")
BednarikovaMaITV = img("faces/BednarikovaMaITV.jpg")
BerankovaAjFr = img("faces/BerankovaAjFr.jpg")
BraunerChBi = img("faces/BraunerChBi.jpg")
CastellarSp = img("faces/CastellarSp.jpg")
CechovaAj = img("faces/CechovaAj.jpg")
ChromaTvZ = img("faces/ChromaTvZ.jpg")
DanielTvZ = img("faces/DanielTvZ.jpg")
DohnalovaCjHv = img("faces/DohnalovaCjHv.jpg")
DostalovaTv = img("faces/DostalovaTv.jpg")
DubovaNeCj = img("faces/DubovaNeCj.jpg")
DvorskyAjD = img("faces/DvorskyAjD.jpg")
FaberovaAjRu = img("faces/FaberovaAjRu.jpg")
FerencMaFy = img("faces/FerencMaFy.jpg")
FukaCjNe = img("faces/FukaCjNe.jpg")
GlosCjD = img("faces/GlosCjD.jpg")
HajduMaAj = img("faces/HajduMaAj.jpg")
HajekBiCh = img("faces/HajekBiCh.jpg")
HamrikovaMaCh = img("faces/HamrikovaMaCh.jpg")
HavranovaAj = img("faces/HavranovaAj.jpg")
HermanovaCjHvRu = img("faces/HermanovaCjHvRu.jpg")
HorvathSp = img("faces/HorvathSp.jpg")
HubackovaCjD = img("faces/HubackovaCjD.jpg")
IA4BerkovaAnna = img("faces/IA4BerkovaAnna.png")
IA4BilikovaAlzbeta = img("faces/IA4BilikovaAlzbeta.png")
IA4BrstakovaJulie = img("faces/IA4BrstakovaJulie.png")
IA4BubenickovaAneta = img("faces/IA4BubenickovaAneta.png")
IA4BuczkovaBarbora = img("faces/IA4BuczkovaBarbora.png")
IA4ChmelikLukas = img("faces/IA4ChmelikLukas.png")
IA4DankovaKarolina = img("faces/IA4DankovaKarolina.png")
IA4GalnorJakub = img("faces/IA4GalnorJakub.png")
IA4GjurgjealaKaona = img("faces/IA4GjurgjealaKaona.png")
IA4HalovaBarbora = img("faces/IA4HalovaBarbora.png")
IA4HimrMatej = img("faces/IA4HimrMatej.png")
IA4HodurovaKEliska = img("faces/IA4HodurovaKEliska.png")
IA4JanalikTomas = img("faces/IA4JanalikTomas.png")
IA4KostkaJan = img("faces/IA4KostkaJan.png")
IA4KoukalFrantisek = img("faces/IA4KoukalFrantisek.png")
IA4KrejciMatyas = img("faces/IA4KrejciMatyas.png")
IA4LipkovaValerie = img("faces/IA4LipkovaValerie.png")
IA4LosikLeonard = img("faces/IA4LosikLeonard.png")
IA4MachovaDagmar = img("faces/IA4MachovaDagmar.png")
IA4PolednaJan = img("faces/IA4PolednaJan.png")
IA4StavarskaLucie = img("faces/IA4StavarskaLucie.png")
IA4StechovaBarbora = img("faces/IA4StechovaBarbora.png")
IA4StejskalovaLinda = img("faces/IA4StejskalovaLinda.png")
IA4VaculikPetr = img("faces/IA4VaculikPetr.png")
IA4WestphalDavid = img("faces/IA4WestphalDavid.png")
IA6BaresovaKlara = img("faces/IA6BaresovaKlara.png")
IA6BelohlavkovaMarie = img("faces/IA6BelohlavkovaMarie.png")
IA6CapalovaKarolina = img("faces/IA6CapalovaKarolina.png")
IA6FedorcoMarian = img("faces/IA6FedorcoMarian.png")
IA6FilousovaLena = img("faces/IA6FilousovaLena.png")
IA6HorklovaKatka = img("faces/IA6HorklovaKatka.png")
IA6KlosovaMarie = img("faces/IA6KlosovaMarie.png")
IA6KvapilMichael = img("faces/IA6KvapilMichael.png")
IA6LukasovaAdela = img("faces/IA6LukasovaAdela.png")
IA6MachStepan = img("faces/IA6MachStepan.png")
IA6MaslikovaTereza = img("faces/IA6MaslikovaTereza.png")
IA6NavratilJachym = img("faces/IA6NavratilJachym.png")
IA6PridalMatej = img("faces/IA6PridalMatej.png")
IA6PtackovaEliska = img("faces/IA6PtackovaEliska.png")
IA6SimakStepan = img("faces/IA6SimakStepan.png")
IA6SouckovaSara = img("faces/IA6SouckovaSara.png")
IA6SouckovaZdenka = img("faces/IA6SouckovaZdenka.png")
IA6SouskovaEliska = img("faces/IA6SouskovaEliska.png")
IA6StarostovaTereza = img("faces/IA6StarostovaTereza.png")
IA6StybnarMarek = img("faces/IA6StybnarMarek.png")
IA6SvobodaDavid = img("faces/IA6SvobodaDavid.png")
IA6UherJan = img("faces/IA6UherJan.png")
IA6ValekDan = img("faces/IA6ValekDan.png")
IA6VrajovaJana = img("faces/IA6VrajovaJana.png")
IA6VyroubalRadek = img("faces/IA6VyroubalRadek.png")
IA6WittmannovaJAnna = img("faces/IA6WittmannovaJAnna.png")
IA6ZelenkovaTereza = img("faces/IA6ZelenkovaTereza.png")
IA6ZemberovaDaniela = img("faces/IA6ZemberovaDaniela.png")
IA8AuxtovaLinda = img("faces/IA8AuxtovaLinda.png")
IA8BartosJan = img("faces/IA8BartosJan.png")
IA8BenesovaJohana = img("faces/IA8BenesovaJohana.png")
IA8BouchalovaKveta = img("faces/IA8BouchalovaKveta.png")
IA8ChmelovaVendula = img("faces/IA8ChmelovaVendula.png")
IA8CisarVojtech = img("faces/IA8CisarVojtech.png")
IA8DostalJakub = img("faces/IA8DostalJakub.png")
IA8FilousovaAlzbeta = img("faces/IA8FilousovaAlzbeta.png")
IA8GajdusekMiroslav = img("faces/IA8GajdusekMiroslav.png")
IA8GogolJMatyas = img("faces/IA8GogolJMatyas.png")
IA8GrassovaEla = img("faces/IA8GrassovaEla.png")
IA8HalatovaVeronika = img("faces/IA8HalatovaVeronika.png")
IA8HandlovaKaterina = img("faces/IA8HandlovaKaterina.png")
IA8HarnosovaAlzbeta = img("faces/IA8HarnosovaAlzbeta.png")
IA8HulikovaAmelie = img("faces/IA8HulikovaAmelie.png")
IA8IlleovaAdela = img("faces/IA8IlleovaAdela.png")
IA8JensDavid = img("faces/IA8JensDavid.png")
IA8KmentovaMarie = img("faces/IA8KmentovaMarie.png")
IA8KornhonTomas = img("faces/IA8KornhonTomas.png")
IA8KropacDavid = img("faces/IA8KropacDavid.png")
IA8LonicekMartin = img("faces/IA8LonicekMartin.png")
IA8MaslikovaKarolina = img("faces/IA8MaslikovaKarolina.png")
IA8MohylovaLaura = img("faces/IA8MohylovaLaura.png")
IA8MuchovaJohana = img("faces/IA8MuchovaJohana.png")
IA8NavratilDaniel = img("faces/IA8NavratilDaniel.png")
IA8ProchazkaJan = img("faces/IA8ProchazkaJan.png")
IA8StefanuttovaAmalie = img("faces/IA8StefanuttovaAmalie.png")
IA8SterbovaSDana = img("faces/IA8SterbovaSDana.png")
IA8TichyMaxmilian = img("faces/IA8TichyMaxmilian.png")
IA8ZdrazilovaAKarolina = img("faces/IA8ZdrazilovaAKarolina.png")
IB4ApplovaPavlina = img("faces/IB4ApplovaPavlina.png")
IB4BacikZeyner = img("faces/IB4BacikZeyner.png")
IB4HavlikMatyas = img("faces/IB4HavlikMatyas.png")
IB4HrancovaMarketa = img("faces/IB4HrancovaMarketa.png")
IB4HrnkovaGita = img("faces/IB4HrnkovaGita.png")
IB4JarosMichael = img("faces/IB4JarosMichael.png")
IB4KalabisovaAnna = img("faces/IB4KalabisovaAnna.png")
IB4KejklickovaTereza = img("faces/IB4KejklickovaTereza.png")
IB4MachVKrystof = img("faces/IB4MachVKrystof.png")
IB4MadrovaAdriana = img("faces/IB4MadrovaAdriana.png")
IB4MalaLenka = img("faces/IB4MalaLenka.png")
IB4MykhailetsVadim = img("faces/IB4MykhailetsVadim.png")
IB4PopelkaStepan = img("faces/IB4PopelkaStepan.png")
IB4PospisilovaZuzana = img("faces/IB4PospisilovaZuzana.png")
IB4PrincDaniel = img("faces/IB4PrincDaniel.png")
IB4SalamonJan = img("faces/IB4SalamonJan.png")
IB4SittekJakub = img("faces/IB4SittekJakub.png")
IB4SkladanyLukas = img("faces/IB4SkladanyLukas.png")
IB4SkrontovaEliska = img("faces/IB4SkrontovaEliska.png")
IB4SkurkovaAdela = img("faces/IB4SkurkovaAdela.png")
IB4SpevakovaEva = img("faces/IB4SpevakovaEva.png")
IB4StojakovaLucie = img("faces/IB4StojakovaLucie.png")
IB4StolfovaNatalie = img("faces/IB4StolfovaNatalie.png")
IB4TajovskaNikola = img("faces/IB4TajovskaNikola.png")
IB4VejmolovaKarolina = img("faces/IB4VejmolovaKarolina.png")
IB6BrodaJakub = img("faces/IB6BrodaJakub.png")
IB6CventanovaKaterina = img("faces/IB6CventanovaKaterina.png")
IB6FisaraDavid = img("faces/IB6FisaraDavid.png")
IB6KonecnaLucie = img("faces/IB6KonecnaLucie.png")
IB6KonecnyVit = img("faces/IB6KonecnyVit.png")
IB6KriegovaPavlina = img("faces/IB6KriegovaPavlina.png")
IB6KrizAntonin = img("faces/IB6KrizAntonin.png")
IB6KubelkaErik = img("faces/IB6KubelkaErik.png")
IB6LejskovaAdela = img("faces/IB6LejskovaAdela.png")
IB6LosikovaLada = img("faces/IB6LosikovaLada.png")
IB6MacickovaJana = img("faces/IB6MacickovaJana.png")
IB6MiksikovaNatalie = img("faces/IB6MiksikovaNatalie.png")
IB6MikulovaBerenika = img("faces/IB6MikulovaBerenika.png")
IB6NajerMarek = img("faces/IB6NajerMarek.png")
IB6NepovimovaLucie = img("faces/IB6NepovimovaLucie.png")
IB6NovotnyOndrej = img("faces/IB6NovotnyOndrej.png")
IB6PribylVojtech = img("faces/IB6PribylVojtech.png")
IB6RobertsonTomas = img("faces/IB6RobertsonTomas.png")
IB6RybaFrantisek = img("faces/IB6RybaFrantisek.png")
IB6SedajovaSarka = img("faces/IB6SedajovaSarka.png")
IB6SobekTomas = img("faces/IB6SobekTomas.png")
IB6SohnelDavid = img("faces/IB6SohnelDavid.png")
IB6StefanovaEma = img("faces/IB6StefanovaEma.png")
IB6StrnadelMichael = img("faces/IB6StrnadelMichael.png")
IB6SyrovatkovaEliska = img("faces/IB6SyrovatkovaEliska.png")
IB6UrbamkovaAnezka = img("faces/IB6UrbamkovaAnezka.png")
IB6UtikalovaLLeontyna = img("faces/IB6UtikalovaLLeontyna.png")
IB6VohankovaKlara = img("faces/IB6VohankovaKlara.png")
IB6ZborilovaSara = img("faces/IB6ZborilovaSara.png")
IB8BrundaMikulas = img("faces/IB8BrundaMikulas.png")
IB8BurdaJan = img("faces/IB8BurdaJan.png")
IB8ChrasteckyJan = img("faces/IB8ChrasteckyJan.png")
IB8DoubalovaJarmila = img("faces/IB8DoubalovaJarmila.png")
IB8FischerOndrej = img("faces/IB8FischerOndrej.png")
IB8GastaPetr = img("faces/IB8GastaPetr.png")
IB8IloemezueBeaAdachi = img("faces/IB8IloemezueBeaAdachi.png")
IB8KlimcakRichard = img("faces/IB8KlimcakRichard.png")
IB8KonecnaElla = img("faces/IB8KonecnaElla.png")
IB8KubickovaSofire = img("faces/IB8KubickovaSofire.png")
IB8KubikJachym = img("faces/IB8KubikJachym.png")
IB8LacovaKristina = img("faces/IB8LacovaKristina.png")
IB8LinekOndrej = img("faces/IB8LinekOndrej.png")
IB8MachacovaEdita = img("faces/IB8MachacovaEdita.png")
IB8MorbicrovaAdela = img("faces/IB8MorbicrovaAdela.png")
IB8NgoTuongVan = img("faces/IB8NgoTuongVan.png")
IB8OndrouskovaTereza = img("faces/IB8OndrouskovaTereza.png")
IB8OpavskyVit = img("faces/IB8OpavskyVit.png")
IB8PeterovaMichaela = img("faces/IB8PeterovaMichaela.png")
IB8PiechDaniel = img("faces/IB8PiechDaniel.png")
IB8RaabovaIva = img("faces/IB8RaabovaIva.png")
IB8StoppenovaJulie = img("faces/IB8StoppenovaJulie.png")
IB8TisovskyMikulas = img("faces/IB8TisovskyMikulas.png")
IB8UtikalovaNJustyna = img("faces/IB8UtikalovaNJustyna.png")
IB8VelickyVaclav = img("faces/IB8VelickyVaclav.png")
IB8VodickovaKristyna = img("faces/IB8VodickovaKristyna.png")
IB8ZavadilTomas = img("faces/IB8ZavadilTomas.png")
IB8ZdarilDaniel = img("faces/IB8ZdarilDaniel.png")
IIA4AndršJan = img("faces/IIA4AndršJan.png")
IIA4BiskupovaSimona = img("faces/IIA4BiskupovaSimona.png")
IIA4BlumaJan = img("faces/IIA4BlumaJan.png")
IIA4ChodurkovaAnna = img("faces/IIA4ChodurkovaAnna.png")
IIA4ChytilovaKarolina = img("faces/IIA4ChytilovaKarolina.png")
IIA4DrahotuskaAmalie = img("faces/IIA4DrahotuskaAmalie.png")
IIA4DvorskaVeronika = img("faces/IIA4DvorskaVeronika.png")
IIA4FrancakovaKarla = img("faces/IIA4FrancakovaKarla.png")
IIA4FrkalFIlip = img("faces/IIA4FrkalFIlip.png")
IIA4FrumarovaAdela = img("faces/IIA4FrumarovaAdela.png")
IIA4HolikovaNatalie = img("faces/IIA4HolikovaNatalie.png")
IIA4HrabalovaKlara = img("faces/IIA4HrabalovaKlara.png")
IIA4HrbackovaKristyna = img("faces/IIA4HrbackovaKristyna.png")
IIA4HrbatovaEva = img("faces/IIA4HrbatovaEva.png")
IIA4HunovaDenisa = img("faces/IIA4HunovaDenisa.png")
IIA4JancikovaLucie = img("faces/IIA4JancikovaLucie.png")
IIA4JanecekJakub = img("faces/IIA4JanecekJakub.png")
IIA4KudybBenjamin = img("faces/IIA4KudybBenjamin.png")
IIA4LekešMatyas = img("faces/IIA4LekešMatyas.png")
IIA4MatejJiri = img("faces/IIA4MatejJiri.png")
IIA4MikulkaPetr = img("faces/IIA4MikulkaPetr.png")
IIA4NemecJakub = img("faces/IIA4NemecJakub.png")
IIA4PekarJakub = img("faces/IIA4PekarJakub.png")
IIA4SaladakTobias = img("faces/IIA4SaladakTobias.png")
IIA4SevernakovaVeronika = img("faces/IIA4SevernakovaVeronika.png")
IIA4SmetakMarek = img("faces/IIA4SmetakMarek.png")
IIA4ZymovaAneta = img("faces/IIA4ZymovaAneta.png")
IIA6BazgerovaEllen = img("faces/IIA6BazgerovaEllen.png")
IIA6DolezalovaElla = img("faces/IIA6DolezalovaElla.png")
IIA6DracJan = img("faces/IIA6DracJan.png")
IIA6DreslerVaclva = img("faces/IIA6DreslerVaclva.png")
IIA6FilipovaKarolina = img("faces/IIA6FilipovaKarolina.png")
IIA6FrybortovaElisa = img("faces/IIA6FrybortovaElisa.png")
IIA6HamalovaAlzbeta = img("faces/IIA6HamalovaAlzbeta.png")
IIA6HomolacovaDarina = img("faces/IIA6HomolacovaDarina.png")
IIA6HorakovaEma = img("faces/IIA6HorakovaEma.png")
IIA6HorvathMatus = img("faces/IIA6HorvathMatus.png")
IIA6KolousekMarek = img("faces/IIA6KolousekMarek.png")
IIA6KysucanovaMilena = img("faces/IIA6KysucanovaMilena.png")
IIA6LerchStepan = img("faces/IIA6LerchStepan.png")
IIA6MaskovaEEmma = img("faces/IIA6MaskovaEEmma.png")
IIA6PavelkovaZuzana = img("faces/IIA6PavelkovaZuzana.png")
IIA6PilchovaZuzana = img("faces/IIA6PilchovaZuzana.png")
IIA6PlesnikAdam = img("faces/IIA6PlesnikAdam.png")
IIA6SvetlikovaEma = img("faces/IIA6SvetlikovaEma.png")
IIA6TranNguyenHongMai = img("faces/IIA6TranNguyenHongMai.png")
IIA6VaclavikovaNicol = img("faces/IIA6VaclavikovaNicol.png")
IIA6VitkovaAneta = img("faces/IIA6VitkovaAneta.png")
IIA6VlkovaEliska = img("faces/IIA6VlkovaEliska.png")
IIA6VrtalovaPetra = img("faces/IIA6VrtalovaPetra.png")
IIA6WiedermannovaEla = img("faces/IIA6WiedermannovaEla.png")
IIA6ZatloukalovaNela = img("faces/IIA6ZatloukalovaNela.png")
IIA6ZeitlerSamuel = img("faces/IIA6ZeitlerSamuel.png")
IIA6ZidkovaBarbora = img("faces/IIA6ZidkovaBarbora.png")
IIA8BalnerJakub = img("faces/IIA8BalnerJakub.png")
IIA8CablikovaAnna = img("faces/IIA8CablikovaAnna.png")
IIA8CernaStella = img("faces/IIA8CernaStella.png")
IIA8CoufalovaBerenika = img("faces/IIA8CoufalovaBerenika.png")
IIA8DupalovaMichaela = img("faces/IIA8DupalovaMichaela.png")
IIA8HajekKrystof = img("faces/IIA8HajekKrystof.png")
IIA8HamplJonas = img("faces/IIA8HamplJonas.png")
IIA8HebelkaEdward = img("faces/IIA8HebelkaEdward.png")
IIA8HyzlovaKaterina = img("faces/IIA8HyzlovaKaterina.png")
IIA8KrumniklMartin = img("faces/IIA8KrumniklMartin.png")
IIA8KuceraMiroslav = img("faces/IIA8KuceraMiroslav.png")
IIA8LokocMartin = img("faces/IIA8LokocMartin.png")
IIA8MisurcovaMarie = img("faces/IIA8MisurcovaMarie.png")
IIA8OklestkovaZuzana = img("faces/IIA8OklestkovaZuzana.png")
IIA8PerneckaAnna = img("faces/IIA8PerneckaAnna.png")
IIA8PilkovaMagdalena = img("faces/IIA8PilkovaMagdalena.png")
IIA8PospisilovaAnna = img("faces/IIA8PospisilovaAnna.png")
IIA8ProtivanekVojtech = img("faces/IIA8ProtivanekVojtech.png")
IIA8SasinkaJaromir = img("faces/IIA8SasinkaJaromir.png")
IIA8SeckarovaVeronika = img("faces/IIA8SeckarovaVeronika.png")
IIA8SlukaOndrej = img("faces/IIA8SlukaOndrej.png")
IIA8SmerekFrantisek = img("faces/IIA8SmerekFrantisek.png")
IIA8SrovnalikovaSofie = img("faces/IIA8SrovnalikovaSofie.png")
IIA8TomankovaMahulena = img("faces/IIA8TomankovaMahulena.png")
IIA8UlicnyTOldrich = img("faces/IIA8UlicnyTOldrich.png")
IIA8VaclavikovaAnna = img("faces/IIA8VaclavikovaAnna.png")
IIA8VevodovaSofie = img("faces/IIA8VevodovaSofie.png")
IIA8ZubakSamuel = img("faces/IIA8ZubakSamuel.png")
IIB4CernyMichael = img("faces/IIB4CernyMichael.png")
IIB4FrantikMichael = img("faces/IIB4FrantikMichael.png")
IIB4HajkovaNela = img("faces/IIB4HajkovaNela.png")
IIB4HawigerStepan = img("faces/IIB4HawigerStepan.png")
IIB4HlusiZaneta = img("faces/IIB4HlusiZaneta.png")
IIB4HulmanAlexander = img("faces/IIB4HulmanAlexander.png")
IIB4KastilovaMichaela = img("faces/IIB4KastilovaMichaela.png")
IIB4LatalovaAgata = img("faces/IIB4LatalovaAgata.png")
IIB4LiskovaNatalie = img("faces/IIB4LiskovaNatalie.png")
IIB4LondaDavid = img("faces/IIB4LondaDavid.png")
IIB4MachasTomas = img("faces/IIB4MachasTomas.png")
IIB4MaderkovaTereza = img("faces/IIB4MaderkovaTereza.png")
IIB4MichalcovaMonika = img("faces/IIB4MichalcovaMonika.png")
IIB4PospisilAdam = img("faces/IIB4PospisilAdam.png")
IIB4RuzickovaJulie = img("faces/IIB4RuzickovaJulie.png")
IIB4SadilovaAneta = img("faces/IIB4SadilovaAneta.png")
IIB4SalkovaJitka = img("faces/IIB4SalkovaJitka.png")
IIB4SedlackovaKaterina = img("faces/IIB4SedlackovaKaterina.png")
IIB4SemianovaVeronika = img("faces/IIB4SemianovaVeronika.png")
IIB4SirokaTereza = img("faces/IIB4SirokaTereza.png")
IIB4SkacelMatej = img("faces/IIB4SkacelMatej.png")
IIB4SnajdarRadek = img("faces/IIB4SnajdarRadek.png")
IIB4SpacekVojtech = img("faces/IIB4SpacekVojtech.png")
IIB4StrizJan = img("faces/IIB4StrizJan.png")
IIB4ZemanekJan = img("faces/IIB4ZemanekJan.png")
IIB6BuchtikJan = img("faces/IIB6BuchtikJan.png")
IIB6FoukalovaNela = img("faces/IIB6FoukalovaNela.png")
IIB6FryblikovaDominika = img("faces/IIB6FryblikovaDominika.png")
IIB6FrysakovaKristyna = img("faces/IIB6FrysakovaKristyna.png")
IIB6HavlikovaSara = img("faces/IIB6HavlikovaSara.png")
IIB6HefkovaNela = img("faces/IIB6HefkovaNela.png")
IIB6HermanovskaKLinda = img("faces/IIB6HermanovskaKLinda.png")
IIB6KadlecFilip = img("faces/IIB6KadlecFilip.png")
IIB6KafetsioisNikiforos = img("faces/IIB6KafetsioisNikiforos.png")
IIB6KlobouckovaAdela = img("faces/IIB6KlobouckovaAdela.png")
IIB6KlvackovaEma = img("faces/IIB6KlvackovaEma.png")
IIB6KrumniklovaDora = img("faces/IIB6KrumniklovaDora.png")
IIB6LabancovaBarbora = img("faces/IIB6LabancovaBarbora.png")
IIB6MezlovaAnezka = img("faces/IIB6MezlovaAnezka.png")
IIB6MichnaMarek = img("faces/IIB6MichnaMarek.png")
IIB6NedomaOndrej = img("faces/IIB6NedomaOndrej.png")
IIB6NemravaStepan = img("faces/IIB6NemravaStepan.png")
IIB6NguyenovaHamy = img("faces/IIB6NguyenovaHamy.png")
IIB6OvacacikovaLucie = img("faces/IIB6OvacacikovaLucie.png")
IIB6QuinnSophieEllen = img("faces/IIB6QuinnSophieEllen.png")
IIB6SimonikovaSara = img("faces/IIB6SimonikovaSara.png")
IIB6SinclovaAnna = img("faces/IIB6SinclovaAnna.png")
IIB6StepanekJaroslav = img("faces/IIB6StepanekJaroslav.png")
IIB6StrakovaEma = img("faces/IIB6StrakovaEma.png")
IIB6TonnerovaENatalie = img("faces/IIB6TonnerovaENatalie.png")
IIB6VyskupSamuel = img("faces/IIB6VyskupSamuel.png")
IIC6BicLukas = img("faces/IIC6BicLukas.png")
IIC6BodnarVilem = img("faces/IIC6BodnarVilem.png")
IIC6HautlerPatrik = img("faces/IIC6HautlerPatrik.png")
IIC6HradilJan = img("faces/IIC6HradilJan.png")
IIC6JanicekMatyas = img("faces/IIC6JanicekMatyas.png")
IIC6KorcovaHana = img("faces/IIC6KorcovaHana.png")
IIC6KunstRichard = img("faces/IIC6KunstRichard.png")
IIC6KyselyMartin = img("faces/IIC6KyselyMartin.png")
IIC6LabounkovaKlara = img("faces/IIC6LabounkovaKlara.png")
IIC6PavlikMartin = img("faces/IIC6PavlikMartin.png")
IIC6PechovaLucie = img("faces/IIC6PechovaLucie.png")
IIC6PerinovaNikol = img("faces/IIC6PerinovaNikol.png")
IIC6PhanThiNhuMai = img("faces/IIC6PhanThiNhuMai.png")
IIC6RajnochDavid = img("faces/IIC6RajnochDavid.png")
IIC6SiskovaMarketa = img("faces/IIC6SiskovaMarketa.png")
IIC6SmeralovaTereza = img("faces/IIC6SmeralovaTereza.png")
IIC6SmitalMartin = img("faces/IIC6SmitalMartin.png")
IIC6SofronieskiAlex = img("faces/IIC6SofronieskiAlex.png")
IIC6StastnyRIchard = img("faces/IIC6StastnyRIchard.png")
IIC6SuchaTereza = img("faces/IIC6SuchaTereza.png")
IIC6SvrcekVojtech = img("faces/IIC6SvrcekVojtech.png")
IIC6TisonovaMarie = img("faces/IIC6TisonovaMarie.png")
IIIA4BizonPavel = img("faces/IIIA4BizonPavel.png")
IIIA4BrezovskyDaniel = img("faces/IIIA4BrezovskyDaniel.png")
IIIA4DzurianovaLucie = img("faces/IIIA4DzurianovaLucie.png")
IIIA4HavlovaKlara = img("faces/IIIA4HavlovaKlara.png")
IIIA4HorakovaNatalie = img("faces/IIIA4HorakovaNatalie.png")
IIIA4HorakStepan = img("faces/IIIA4HorakStepan.png")
IIIA4JakobBenjamin = img("faces/IIIA4JakobBenjamin.png")
IIIA4JanackovaLucie = img("faces/IIIA4JanackovaLucie.png")
IIIA4JenikovaMonika = img("faces/IIIA4JenikovaMonika.png")
IIIA4JurtikovaJarmila = img("faces/IIIA4JurtikovaJarmila.png")
IIIA4KalvachMichal = img("faces/IIIA4KalvachMichal.png")
IIIA4KnoflickovaJana = img("faces/IIIA4KnoflickovaJana.png")
IIIA4KozlovskaElena = img("faces/IIIA4KozlovskaElena.png")
IIIA4LatalovaNikola = img("faces/IIIA4LatalovaNikola.png")
IIIA4LatalovaZuzana = img("faces/IIIA4LatalovaZuzana.png")
IIIA4MajdiakJosef = img("faces/IIIA4MajdiakJosef.png")
IIIA4MonicovaKaterina = img("faces/IIIA4MonicovaKaterina.png")
IIIA4MudrakVit = img("faces/IIIA4MudrakVit.png")
IIIA4NeoralovaZuzana = img("faces/IIIA4NeoralovaZuzana.png")
IIIA4NevecnaSarka = img("faces/IIIA4NevecnaSarka.png")
IIIA4NezhybovaKristyna = img("faces/IIIA4NezhybovaKristyna.png")
IIIA4PallaJiri = img("faces/IIIA4PallaJiri.png")
IIIA4PichovaAndrea = img("faces/IIIA4PichovaAndrea.png")
IIIA4RudykovaAlexandra = img("faces/IIIA4RudykovaAlexandra.png")
IIIA4StimplovaMarketa = img("faces/IIIA4StimplovaMarketa.png")
IIIA4SuchankovaJasmina = img("faces/IIIA4SuchankovaJasmina.png")
IIIA4SvabenskaEliska = img("faces/IIIA4SvabenskaEliska.png")
IIIA4TelickaTobias = img("faces/IIIA4TelickaTobias.png")
IIIA4UtikalovaEliska = img("faces/IIIA4UtikalovaEliska.png")
IIIA4VitoulovaTereza = img("faces/IIIA4VitoulovaTereza.png")
IIIA4WeinlichovaNatalie = img("faces/IIIA4WeinlichovaNatalie.png")
IIIA6AxmanPetr = img("faces/IIIA6AxmanPetr.png")
IIIA6BuresADavid = img("faces/IIIA6BuresADavid.png")
IIIA6CermakJaroslav = img("faces/IIIA6CermakJaroslav.png")
IIIA6ChupikMichal = img("faces/IIIA6ChupikMichal.png")
IIIA6HanikovaAdela = img("faces/IIIA6HanikovaAdela.png")
IIIA6HanzelkaFilip = img("faces/IIIA6HanzelkaFilip.png")
IIIA6HeczkovaIzabela = img("faces/IIIA6HeczkovaIzabela.png")
IIIA6HorakovaValerie = img("faces/IIIA6HorakovaValerie.png")
IIIA6HulikovaVanessa = img("faces/IIIA6HulikovaVanessa.png")
IIIA6JankuOto = img("faces/IIIA6JankuOto.png")
IIIA6JavorikovaSara = img("faces/IIIA6JavorikovaSara.png")
IIIA6JenikovaHelena = img("faces/IIIA6JenikovaHelena.png")
IIIA6KanjanepokinSutheera = img("faces/IIIA6KanjanepokinSutheera.png")
IIIA6KovarikovaHana = img("faces/IIIA6KovarikovaHana.png")
IIIA6KriklovaLucie = img("faces/IIIA6KriklovaLucie.png")
IIIA6KurfurstovaElena = img("faces/IIIA6KurfurstovaElena.png")
IIIA6MarabetiRosalia = img("faces/IIIA6MarabetiRosalia.png")
IIIA6MikesovaNela = img("faces/IIIA6MikesovaNela.png")
IIIA6MohaplovaNikola = img("faces/IIIA6MohaplovaNikola.png")
IIIA6NovotnyDavid = img("faces/IIIA6NovotnyDavid.png")
IIIA6OdstrcilovaBarbora = img("faces/IIIA6OdstrcilovaBarbora.png")
IIIA6SchwartzhoffovaMarie = img("faces/IIIA6SchwartzhoffovaMarie.png")
IIIA6SkyvovaBarbora = img("faces/IIIA6SkyvovaBarbora.png")
IIIA6StaskovaMarie = img("faces/IIIA6StaskovaMarie.png")
IIIA6SvobodaDaniel = img("faces/IIIA6SvobodaDaniel.png")
IIIA6VaclavikLukas = img("faces/IIIA6VaclavikLukas.png")
IIIA6ValentovaMarketa = img("faces/IIIA6ValentovaMarketa.png")
IIIA6ZahradnickovaAnna = img("faces/IIIA6ZahradnickovaAnna.png")
IIIA8BazantovaMagdalena = img("faces/IIIA8BazantovaMagdalena.png")
IIIA8BlahutovaEKarolina = img("faces/IIIA8BlahutovaEKarolina.png")
IIIA8BodnarovaEma = img("faces/IIIA8BodnarovaEma.png")
IIIA8BubenicekDavid = img("faces/IIIA8BubenicekDavid.png")
IIIA8DejlMartin = img("faces/IIIA8DejlMartin.png")
IIIA8DrozdovaNela = img("faces/IIIA8DrozdovaNela.png")
IIIA8DudaBenjamin = img("faces/IIIA8DudaBenjamin.png")
IIIA8DvorakovaTereza = img("faces/IIIA8DvorakovaTereza.png")
IIIA8FiserovaJana = img("faces/IIIA8FiserovaJana.png")
IIIA8HoangovaAnh = img("faces/IIIA8HoangovaAnh.png")
IIIA8HolasekTomas = img("faces/IIIA8HolasekTomas.png")
IIIA8HorakAlexandr = img("faces/IIIA8HorakAlexandr.png")
IIIA8HrabalNikola = img("faces/IIIA8HrabalNikola.png")
IIIA8JanosikLukas = img("faces/IIIA8JanosikLukas.png")
IIIA8KralovaIvana = img("faces/IIIA8KralovaIvana.png")
IIIA8KratkyLukas = img("faces/IIIA8KratkyLukas.png")
IIIA8KubikovaEliska = img("faces/IIIA8KubikovaEliska.png")
IIIA8KudlaRudolf = img("faces/IIIA8KudlaRudolf.png")
IIIA8KvapilovaTereza = img("faces/IIIA8KvapilovaTereza.png")
IIIA8MutinaMarek = img("faces/IIIA8MutinaMarek.png")
IIIA8MyskovaTereza = img("faces/IIIA8MyskovaTereza.png")
IIIA8NovakovaDaniela = img("faces/IIIA8NovakovaDaniela.png")
IIIA8SlezarovaAnna = img("faces/IIIA8SlezarovaAnna.png")
IIIA8SmekalovaLucie = img("faces/IIIA8SmekalovaLucie.png")
IIIA8StavarskyRichard = img("faces/IIIA8StavarskyRichard.png")
IIIA8ValentovaVeronika = img("faces/IIIA8ValentovaVeronika.png")
IIIA8VohralikovaJohana = img("faces/IIIA8VohralikovaJohana.png")
IIIA8ZikmundovaAdela = img("faces/IIIA8ZikmundovaAdela.png")
IIIB4AssenzaSilvia = img("faces/IIIB4AssenzaSilvia.png")
IIIB4BergmanVaclav = img("faces/IIIB4BergmanVaclav.png")
IIIB4ChudobovaJulie = img("faces/IIIB4ChudobovaJulie.png")
IIIB4DornakovaLLeona = img("faces/IIIB4DornakovaLLeona.png")
IIIB4DuskovaKristyna = img("faces/IIIB4DuskovaKristyna.png")
IIIB4FlorianovaRadka = img("faces/IIIB4FlorianovaRadka.png")
IIIB4HetovaBarbora = img("faces/IIIB4HetovaBarbora.png")
IIIB4JuchymivovaKarolina = img("faces/IIIB4JuchymivovaKarolina.png")
IIIB4KikaSimon = img("faces/IIIB4KikaSimon.png")
IIIB4KucerovaAneta = img("faces/IIIB4KucerovaAneta.png")
IIIB4LavrincikovaLaura = img("faces/IIIB4LavrincikovaLaura.png")
IIIB4LyskovaKlaudie = img("faces/IIIB4LyskovaKlaudie.png")
IIIB4MiketovaAdela = img("faces/IIIB4MiketovaAdela.png")
IIIB4MiketovaAnna = img("faces/IIIB4MiketovaAnna.png")
IIIB4NovakOndrej = img("faces/IIIB4NovakOndrej.png")
IIIB4NovakovaIveta = img("faces/IIIB4NovakovaIveta.png")
IIIB4PolednaOndrej = img("faces/IIIB4PolednaOndrej.png")
IIIB4RehacekAdam = img("faces/IIIB4RehacekAdam.png")
IIIB4RosipalovaLucie = img("faces/IIIB4RosipalovaLucie.png")
IIIB4SandrovaLucie = img("faces/IIIB4SandrovaLucie.png")
IIIB4SkrabalovaKristyna = img("faces/IIIB4SkrabalovaKristyna.png")
IIIB4SlamencovaNikol = img("faces/IIIB4SlamencovaNikol.png")
IIIB4SnoblovaAnna = img("faces/IIIB4SnoblovaAnna.png")
IIIB4SpangerovaMarie = img("faces/IIIB4SpangerovaMarie.png")
IIIB4UrbanDaniel = img("faces/IIIB4UrbanDaniel.png")
IIIB4VavrinTadeas = img("faces/IIIB4VavrinTadeas.png")
IIIB4VichovaEliska = img("faces/IIIB4VichovaEliska.png")
IIIB4WagnerovaKlara = img("faces/IIIB4WagnerovaKlara.png")
IIIB4ZborilovaKlara = img("faces/IIIB4ZborilovaKlara.png")
IIIB4ZonaDavid = img("faces/IIIB4ZonaDavid.png")
IIIB6BognarovaJulie = img("faces/IIIB6BognarovaJulie.png")
IIIB6CvetanRobert = img("faces/IIIB6CvetanRobert.png")
IIIB6CvrckovaEliska = img("faces/IIIB6CvrckovaEliska.png")
IIIB6HamplovaAnna = img("faces/IIIB6HamplovaAnna.png")
IIIB6HanykTomas = img("faces/IIIB6HanykTomas.png")
IIIB6HejdukovaLeona = img("faces/IIIB6HejdukovaLeona.png")
IIIB6HrdlickaAdam = img("faces/IIIB6HrdlickaAdam.png")
IIIB6JarosovaAdriana = img("faces/IIIB6JarosovaAdriana.png")
IIIB6KorinkovaTana = img("faces/IIIB6KorinkovaTana.png")
IIIB6LatalovaNatalie = img("faces/IIIB6LatalovaNatalie.png")
IIIB6MistaMatous = img("faces/IIIB6MistaMatous.png")
IIIB6NovotnaAgata = img("faces/IIIB6NovotnaAgata.png")
IIIB6PiechovaJulie = img("faces/IIIB6PiechovaJulie.png")
IIIB6PisoftovaEva = img("faces/IIIB6PisoftovaEva.png")
IIIB6PivodovaKaterina = img("faces/IIIB6PivodovaKaterina.png")
IIIB6RuzickovaEma = img("faces/IIIB6RuzickovaEma.png")
IIIB6SedlakOndrej = img("faces/IIIB6SedlakOndrej.png")
IIIB6SeluckaBarbora = img("faces/IIIB6SeluckaBarbora.png")
IIIB6SmekalMartin = img("faces/IIIB6SmekalMartin.png")
IIIB6SowaJakub = img("faces/IIIB6SowaJakub.png")
IIIB6SpacekJakub = img("faces/IIIB6SpacekJakub.png")
IIIB6SpertlikvoaVeronika = img("faces/IIIB6SpertlikvoaVeronika.png")
IIIB6TelcovaKlara = img("faces/IIIB6TelcovaKlara.png")
IIIB6ValentaAdam = img("faces/IIIB6ValentaAdam.png")
IIIB6VranovaMarina = img("faces/IIIB6VranovaMarina.png")
IIIB6VyslouzilovaElena = img("faces/IIIB6VyslouzilovaElena.png")
IIIB6ZizlavskaAmelie = img("faces/IIIB6ZizlavskaAmelie.png")
IIIB8AmbrosMichael = img("faces/IIIB8AmbrosMichael.png")
IIIB8AxmanovaPavlina = img("faces/IIIB8AxmanovaPavlina.png")
IIIB8BuresEBenjamin = img("faces/IIIB8BuresEBenjamin.png")
IIIB8CoufalovaNoemi = img("faces/IIIB8CoufalovaNoemi.png")
IIIB8DolezalovaHelena = img("faces/IIIB8DolezalovaHelena.png")
IIIB8HavrlantSimon = img("faces/IIIB8HavrlantSimon.png")
IIIB8HimrJonas = img("faces/IIIB8HimrJonas.png")
IIIB8HockadaySMatthew = img("faces/IIIB8HockadaySMatthew.png")
IIIB8HoudekJan = img("faces/IIIB8HoudekJan.png")
IIIB8JuraskovaAneta = img("faces/IIIB8JuraskovaAneta.png")
IIIB8KlimkovaViola = img("faces/IIIB8KlimkovaViola.png")
IIIB8KolarJan = img("faces/IIIB8KolarJan.png")
IIIB8KonecnyPetr = img("faces/IIIB8KonecnyPetr.png")
IIIB8LazarovaSofie = img("faces/IIIB8LazarovaSofie.png")
IIIB8MadrovaGabriela = img("faces/IIIB8MadrovaGabriela.png")
IIIB8PaulickovaTereza = img("faces/IIIB8PaulickovaTereza.png")
IIIB8PetrivalskyNil = img("faces/IIIB8PetrivalskyNil.png")
IIIB8PolednovaSofie = img("faces/IIIB8PolednovaSofie.png")
IIIB8RatajovaTerezie = img("faces/IIIB8RatajovaTerezie.png")
IIIB8SaradinMatej = img("faces/IIIB8SaradinMatej.png")
IIIB8SimackovaMEmma = img("faces/IIIB8SimackovaMEmma.png")
IIIB8SitovaHana = img("faces/IIIB8SitovaHana.png")
IIIB8SmutnaHana = img("faces/IIIB8SmutnaHana.png")
IIIB8StefanovaAnna = img("faces/IIIB8StefanovaAnna.png")
IIIB8StyblovaTatiana = img("faces/IIIB8StyblovaTatiana.png")
IIIB8TomeckovaAnna = img("faces/IIIB8TomeckovaAnna.png")
IIIB8VaclavikovaAnna = img("faces/IIIB8VaclavikovaAnna.png")
IIIB8VeseckyJakub = img("faces/IIIB8VeseckyJakub.png")
IIIB8ZidkovaLinda = img("faces/IIIB8ZidkovaLinda.png")
IVA4BrumarVaclav = img("faces/IVA4BrumarVaclav.png")
IVA4CapecAmelia = img("faces/IVA4CapecAmelia.png")
IVA4CechovaMarie = img("faces/IVA4CechovaMarie.png")
IVA4ChrenkoMichael = img("faces/IVA4ChrenkoMichael.png")
IVA4DavidTomas = img("faces/IVA4DavidTomas.png")
IVA4DramliukIlya = img("faces/IVA4DramliukIlya.png")
IVA4HalaxovaEmma = img("faces/IVA4HalaxovaEmma.png")
IVA4JakubecMilan = img("faces/IVA4JakubecMilan.png")
IVA4JasinkovaBarbora = img("faces/IVA4JasinkovaBarbora.png")
IVA4KaplikovaLucie = img("faces/IVA4KaplikovaLucie.png")
IVA4KovarikovaEliska = img("faces/IVA4KovarikovaEliska.png")
IVA4KrytinarPavel = img("faces/IVA4KrytinarPavel.png")
IVA4KubickovaEma = img("faces/IVA4KubickovaEma.png")
IVA4LolkovaKarolina = img("faces/IVA4LolkovaKarolina.png")
IVA4MalaValerie = img("faces/IVA4MalaValerie.png")
IVA4MikulikovaSara = img("faces/IVA4MikulikovaSara.png")
IVA4MorkovskaNikola = img("faces/IVA4MorkovskaNikola.png")
IVA4NovakovaMagdalena = img("faces/IVA4NovakovaMagdalena.png")
IVA4PelisekMatej = img("faces/IVA4PelisekMatej.png")
IVA4PliskovaANikola = img("faces/IVA4PliskovaANikola.png")
IVA4PolackovaAdela = img("faces/IVA4PolackovaAdela.png")
IVA4PolisovaBarbora = img("faces/IVA4PolisovaBarbora.png")
IVA4RacekJakub = img("faces/IVA4RacekJakub.png")
IVA4SalaquardaTadeas = img("faces/IVA4SalaquardaTadeas.png")
IVA4SebanekEduard = img("faces/IVA4SebanekEduard.png")
IVA4SelicharovaLucie = img("faces/IVA4SelicharovaLucie.png")
IVA4SmekalovaBarbora = img("faces/IVA4SmekalovaBarbora.png")
IVA4StrnadovaLucie = img("faces/IVA4StrnadovaLucie.png")
IVA4ZapletalovaZuzana = img("faces/IVA4ZapletalovaZuzana.png")
IVA6BalasovaNela = img("faces/IVA6BalasovaNela.png")
IVA6BergerViktorie = img("faces/IVA6BergerViktorie.png")
IVA6BirckaPetr = img("faces/IVA6BirckaPetr.png")
IVA6CepovaNatalie = img("faces/IVA6CepovaNatalie.png")
IVA6DoubravaBoleslav = img("faces/IVA6DoubravaBoleslav.png")
IVA6HejtmanovaLucie = img("faces/IVA6HejtmanovaLucie.png")
IVA6HlavacovaPetra = img("faces/IVA6HlavacovaPetra.png")
IVA6JavorskyMartin = img("faces/IVA6JavorskyMartin.png")
IVA6JelenkovaAlice = img("faces/IVA6JelenkovaAlice.png")
IVA6KorcanovaNatalie = img("faces/IVA6KorcanovaNatalie.png")
IVA6KrocilovaVendula = img("faces/IVA6KrocilovaVendula.png")
IVA6KunstlerMarek = img("faces/IVA6KunstlerMarek.png")
IVA6KyselyViktor = img("faces/IVA6KyselyViktor.png")
IVA6LatalovaLucie = img("faces/IVA6LatalovaLucie.png")
IVA6LustigovaNellie = img("faces/IVA6LustigovaNellie.png")
IVA6MeleckaAneta = img("faces/IVA6MeleckaAneta.png")
IVA6PetrLovaLucie = img("faces/IVA6PetrLovaLucie.png")
IVA6PribylvoaNela = img("faces/IVA6PribylvoaNela.png")
IVA6RichterovaJulie = img("faces/IVA6RichterovaJulie.png")
IVA6SimkovaEmilie = img("faces/IVA6SimkovaEmilie.png")
IVA6SmatlakovaHana = img("faces/IVA6SmatlakovaHana.png")
IVA6SoukenikovaBarbora = img("faces/IVA6SoukenikovaBarbora.png")
IVA6SousekJan = img("faces/IVA6SousekJan.png")
IVA6StanekKrystof = img("faces/IVA6StanekKrystof.png")
IVA6StybnarovaLucie = img("faces/IVA6StybnarovaLucie.png")
IVA6TylsarovaAnna = img("faces/IVA6TylsarovaAnna.png")
IVA6VendelinFilip = img("faces/IVA6VendelinFilip.png")
IVA6ZlutirovaHelena = img("faces/IVA6ZlutirovaHelena.png")
IVA8BouchalMarek = img("faces/IVA8BouchalMarek.png")
IVA8BrozdaAdam = img("faces/IVA8BrozdaAdam.png")
IVA8CanibalFilip = img("faces/IVA8CanibalFilip.png")
IVA8CoufalovaJudita = img("faces/IVA8CoufalovaJudita.png")
IVA8DvorskyMichal = img("faces/IVA8DvorskyMichal.png")
IVA8GeprtovaMartina = img("faces/IVA8GeprtovaMartina.png")
IVA8HalasVaclav = img("faces/IVA8HalasVaclav.png")
IVA8JuraMarek = img("faces/IVA8JuraMarek.png")
IVA8KaresVit = img("faces/IVA8KaresVit.png")
IVA8KlimcakovaAnna = img("faces/IVA8KlimcakovaAnna.png")
IVA8KoupilFlorian = img("faces/IVA8KoupilFlorian.png")
IVA8KovarikVojtech = img("faces/IVA8KovarikVojtech.png")
IVA8KurfurstAdam = img("faces/IVA8KurfurstAdam.png")
IVA8LosseovaMarie = img("faces/IVA8LosseovaMarie.png")
IVA8MohaplTomas = img("faces/IVA8MohaplTomas.png")
IVA8NavratilovaAmelie = img("faces/IVA8NavratilovaAmelie.png")
IVA8NiemiecJiri = img("faces/IVA8NiemiecJiri.png")
IVA8PippalNikolas = img("faces/IVA8PippalNikolas.png")
IVA8PospisilovaAnezka = img("faces/IVA8PospisilovaAnezka.png")
IVA8ProchazkaJosef = img("faces/IVA8ProchazkaJosef.png")
IVA8ProchazkovaAnezka = img("faces/IVA8ProchazkovaAnezka.png")
IVA8PuskasJSamuel = img("faces/IVA8PuskasJSamuel.png")
IVA8SrotovaLucie = img("faces/IVA8SrotovaLucie.png")
IVA8VanekKarel = img("faces/IVA8VanekKarel.png")
IVA8VortelJakub = img("faces/IVA8VortelJakub.png")
IVA8ZimovaSKarolina = img("faces/IVA8ZimovaSKarolina.png")
IVB4BalnerovaAmalie = img("faces/IVB4BalnerovaAmalie.png")
IVB4BenesKrystof = img("faces/IVB4BenesKrystof.png")
IVB4CharvatPetr = img("faces/IVB4CharvatPetr.png")
IVB4CtvrtlikovaElen = img("faces/IVB4CtvrtlikovaElen.png")
IVB4DrozdovaSvetlana = img("faces/IVB4DrozdovaSvetlana.png")
IVB4GalnorovaKaterina = img("faces/IVB4GalnorovaKaterina.png")
IVB4HladisovaMarketa = img("faces/IVB4HladisovaMarketa.png")
IVB4JanosovaViktorie = img("faces/IVB4JanosovaViktorie.png")
IVB4KaiserovaAdela = img("faces/IVB4KaiserovaAdela.png")
IVB4KazinotaVojtěch = img("faces/IVB4KazinotaVojtěch.png")
IVB4KnotkovaKaterina = img("faces/IVB4KnotkovaKaterina.png")
IVB4KovalovaNikola = img("faces/IVB4KovalovaNikola.png")
IVB4KovarikovaKlara = img("faces/IVB4KovarikovaKlara.png")
IVB4LiskovaJohana = img("faces/IVB4LiskovaJohana.png")
IVB4MachalaJan = img("faces/IVB4MachalaJan.png")
IVB4MensikMatej = img("faces/IVB4MensikMatej.png")
IVB4PeleshkoKristyna = img("faces/IVB4PeleshkoKristyna.png")
IVB4PospisilovaTereza = img("faces/IVB4PospisilovaTereza.png")
IVB4ReznickovaTereza = img("faces/IVB4ReznickovaTereza.png")
IVB4SanakJaroslav = img("faces/IVB4SanakJaroslav.png")
IVB4SkopalovaLucie = img("faces/IVB4SkopalovaLucie.png")
IVB4SmatanovaKlara = img("faces/IVB4SmatanovaKlara.png")
IVB4SpitMartin = img("faces/IVB4SpitMartin.png")
IVB4StruharovaGabriela = img("faces/IVB4StruharovaGabriela.png")
IVB4SvobodovaAneta = img("faces/IVB4SvobodovaAneta.png")
IVB4VachalovaAneta = img("faces/IVB4VachalovaAneta.png")
IVB4VavrovaVendula = img("faces/IVB4VavrovaVendula.png")
IVB4WunschovaKlara = img("faces/IVB4WunschovaKlara.png")
IVB6BednarovaLudmila = img("faces/IVB6BednarovaLudmila.png")
IVB6BinarovaAdela = img("faces/IVB6BinarovaAdela.png")
IVB6BombreovaJana = img("faces/IVB6BombreovaJana.png")
IVB6BurianovaIvana = img("faces/IVB6BurianovaIvana.png")
IVB6CharvatovaKlara = img("faces/IVB6CharvatovaKlara.png")
IVB6DitmarovaValerie = img("faces/IVB6DitmarovaValerie.png")
IVB6DubovaTerezie = img("faces/IVB6DubovaTerezie.png")
IVB6FinkovaVendula = img("faces/IVB6FinkovaVendula.png")
IVB6ForalovaKaterina = img("faces/IVB6ForalovaKaterina.png")
IVB6GosovaEster = img("faces/IVB6GosovaEster.png")
IVB6HartmannovaAlzbeta = img("faces/IVB6HartmannovaAlzbeta.png")
IVB6HlaviznovaTereza = img("faces/IVB6HlaviznovaTereza.png")
IVB6JuricekDavid = img("faces/IVB6JuricekDavid.png")
IVB6KlechPatrik = img("faces/IVB6KlechPatrik.png")
IVB6KosakovaEliska = img("faces/IVB6KosakovaEliska.png")
IVB6KrumnikolvaEma = img("faces/IVB6KrumnikolvaEma.png")
IVB6LosseJosef = img("faces/IVB6LosseJosef.png")
IVB6NaspinskyDavid = img("faces/IVB6NaspinskyDavid.png")
IVB6NepsinskyDavid = img("faces/IVB6NepsinskyDavid.png")
IVB6SkopalovaAdela = img("faces/IVB6SkopalovaAdela.png")
IVB6SlotaVojtech = img("faces/IVB6SlotaVojtech.png")
IVB6StancovaKamila = img("faces/IVB6StancovaKamila.png")
IVB6StastnaKarolina = img("faces/IVB6StastnaKarolina.png")
IVB6StrnadovaKamila = img("faces/IVB6StrnadovaKamila.png")
IVB6UtikalovaLValentyna = img("faces/IVB6UtikalovaLValentyna.png")
IVB6VolmutJakub = img("faces/IVB6VolmutJakub.png")
IVB6VymazalTomas = img("faces/IVB6VymazalTomas.png")
IVB6ZaludaKrystof = img("faces/IVB6ZaludaKrystof.png")
IVB6ZamecnikovaElen = img("faces/IVB6ZamecnikovaElen.png")
IVB6ZborilovaPavla = img("faces/IVB6ZborilovaPavla.png")
IVC4ApplHynek = img("faces/IVC4ApplHynek.png")
IVC4DohnalJan = img("faces/IVC4DohnalJan.png")
IVC4HatalovaMarketa = img("faces/IVC4HatalovaMarketa.png")
IVC4HenklovaEliska = img("faces/IVC4HenklovaEliska.png")
IVC4KaplovaKarolina = img("faces/IVC4KaplovaKarolina.png")
IVC4LustigovaSophia = img("faces/IVC4LustigovaSophia.png")
IVC4PodivinskyAdam = img("faces/IVC4PodivinskyAdam.png")
IVC4PrichystalKarlos = img("faces/IVC4PrichystalKarlos.png")
IVC4PrichystalovaMartina = img("faces/IVC4PrichystalovaMartina.png")
IVC4PrincovaElizabeth = img("faces/IVC4PrincovaElizabeth.png")
IVC4PsotkaVojtech = img("faces/IVC4PsotkaVojtech.png")
IVC4SandorJaromir = img("faces/IVC4SandorJaromir.png")
IVC4SanovecAdam = img("faces/IVC4SanovecAdam.png")
IVC4SpurnaEliska = img("faces/IVC4SpurnaEliska.png")
IVC4StanoLukas = img("faces/IVC4StanoLukas.png")
IVC4TajovskaKaterina = img("faces/IVC4TajovskaKaterina.png")
IVC4UtikalovaKarolina = img("faces/IVC4UtikalovaKarolina.png")
IVC4VaculaAdam = img("faces/IVC4VaculaAdam.png")
IVC4VeselskaAnna = img("faces/IVC4VeselskaAnna.png")
IVC4VykopalPavel = img("faces/IVC4VykopalPavel.png")
IVC4VysoudilovaVendula = img("faces/IVC4VysoudilovaVendula.png")
IVC4ZdarilJakub = img("faces/IVC4ZdarilJakub.png")
IVC4ZinkovaAneta = img("faces/IVC4ZinkovaAneta.png")
JanickovaAjCj = img("faces/JanickovaAjCj.jpg")
JonesAj = img("faces/JonesAj.jpg")
JurikTvZ = img("faces/JurikTvZ.jpg")
KalandrovaCjOv = img("faces/KalandrovaCjOv.jpg")
KnapekAjSp = img("faces/KnapekAjSp.jpg")
KonecnaNeCj = img("faces/KonecnaNeCj.jpg")
KostkovaMaCh = img("faces/KostkovaMaCh.jpg")
KovarovaMaCh = img("faces/KovarovaMaCh.jpg")
KralovaAj = img("faces/KralovaAj.jpg")
KrcovaMaZ = img("faces/KrcovaMaZ.jpg")
KrejcirovaSp = img("faces/KrejcirovaSp.jpg")
KrejcirTvZ = img("faces/KrejcirTvZ.jpg")
KrizovaMaFy = img("faces/KrizovaMaFy.jpg")
KvapilMaFyHv = img("faces/KvapilMaFyHv.jpg")
LekesovaCjHv = img("faces/LekesovaCjHv.jpg")
LetakovaBiCh = img("faces/LetakovaBiCh.jpg")
MadrovaAj = img("faces/MadrovaAj.jpg")
MarkovaBiCh = img("faces/MarkovaBiCh.jpg")
MartinikovaNeHv = img("faces/MartinikovaNeHv.jpg")
MasnyOvVv = img("faces/MasnyOvVv.jpg")
McMullinAj = img("faces/McMullinAj.jpg")
MenouskovaCjFr = img("faces/MenouskovaCjFr.jpg")
MinarikMa = img("faces/MinarikMa.jpg")
NavratilBiZ = img("faces/NavratilBiZ.jpg")
NavratilovaAj = img("faces/NavratilovaAj.jpg")
NezvalovaAjRuD = img("faces/NezvalovaAjRuD.jpg")
OndrakOvLat = img("faces/OndrakOvLat.jpg")
PazderovaMaFy = img("faces/PazderovaMaFy.jpg")
PetrMaFy = img("faces/PetrMaFy.jpg")
PiechovaAj = img("faces/PiechovaAj.jpg")
PohanelMaZAjProjekty = img("faces/PohanelMaZAjProjekty.jpg")
PolednovaMaZ = img("faces/PolednovaMaZ.jpg")
PridalovaAjRu = img("faces/PridalovaAjRu.jpg")
PrzybylovaCjHv = img("faces/PrzybylovaCjHv.jpg")
PuskarovaNeCj = img("faces/PuskarovaNeCj.jpg")
RehulkaBiCh = img("faces/RehulkaBiCh.jpg")
RichterkovaMaFy = img("faces/RichterkovaMaFy.jpg")
SedlackovaCjFr = img("faces/SedlackovaCjFr.jpg")
SeverovaMaIVT = img("faces/SeverovaMaIVT.jpg")
SladecekCjAj = img("faces/SladecekCjAj.jpg")
SoubustovaNeRu = img("faces/SoubustovaNeRu.jpg")
StanecSp = img("faces/StanecSp.jpg")
StepanovIVT = img("faces/StepanovIVT.jpg")
StranskaFy = img("faces/StranskaFy.jpg")
StudnickaMaIVT = img("faces/StudnickaMaIVT.jpg")
SuchankovaAj = img("faces/SuchankovaAj.jpg")
SykorovaAjD = img("faces/SykorovaAjD.jpg")
TeplyAjTv = img("faces/TeplyAjTv.jpg")
UrbaskovaMaZ = img("faces/UrbaskovaMaZ.jpg")
VA6AujeskaKaterina = img("faces/VA6AujeskaKaterina.png")
VA6CernoskovaLinda = img("faces/VA6CernoskovaLinda.png")
VA6ChudzikJan = img("faces/VA6ChudzikJan.png")
VA6DolezelovaAndrea = img("faces/VA6DolezelovaAndrea.png")
VA6GrablPatrik = img("faces/VA6GrablPatrik.png")
VA6GunkovaEliska = img("faces/VA6GunkovaEliska.png")
VA6HarastovaEliska = img("faces/VA6HarastovaEliska.png")
VA6HautlerovaEliska = img("faces/VA6HautlerovaEliska.png")
VA6KralovaSara = img("faces/VA6KralovaSara.png")
VA6KrejciMagdalena = img("faces/VA6KrejciMagdalena.png")
VA6KrupickovaKamila = img("faces/VA6KrupickovaKamila.png")
VA6LejskovaAdina = img("faces/VA6LejskovaAdina.png")
VA6MrazkovaAdela = img("faces/VA6MrazkovaAdela.png")
VA6NavratilPetr = img("faces/VA6NavratilPetr.png")
VA6OpletalovaSElisa = img("faces/VA6OpletalovaSElisa.png")
VA6PalouskovaTereza = img("faces/VA6PalouskovaTereza.png")
VA6PavlickovaATerezie = img("faces/VA6PavlickovaATerezie.png")
VA6PavlickovaMonika = img("faces/VA6PavlickovaMonika.png")
VA6PepekPospisil = img("faces/VA6PepekPospisil.png")
VA6PolasekMartin = img("faces/VA6PolasekMartin.png")
VA6PtasnikSimon = img("faces/VA6PtasnikSimon.png")
VA6PuckovaOlga = img("faces/VA6PuckovaOlga.png")
VA6RoubalikOta = img("faces/VA6RoubalikOta.png")
VA6ValouskkovaMiroslavav = img("faces/VA6ValouskkovaMiroslavav.png")
VA6VasickovaVendula = img("faces/VA6VasickovaVendula.png")
VA6ZakovaAnna = img("faces/VA6ZakovaAnna.png")
VA6ZavodnikovaBerenika = img("faces/VA6ZavodnikovaBerenika.png")
VA8BrundaAlbert = img("faces/VA8BrundaAlbert.png")
VA8DudovaAnezka = img("faces/VA8DudovaAnezka.png")
VA8DvorakovaVera = img("faces/VA8DvorakovaVera.png")
VA8GorcaRafael = img("faces/VA8GorcaRafael.png")
VA8HavrlantovaElen = img("faces/VA8HavrlantovaElen.png")
VA8HockadayMHana = img("faces/VA8HockadayMHana.png")
VA8HrosovaMartina = img("faces/VA8HrosovaMartina.png")
VA8HudcovaNatalie = img("faces/VA8HudcovaNatalie.png")
VA8JirovskyTomas = img("faces/VA8JirovskyTomas.png")
VA8JuklAlexander = img("faces/VA8JuklAlexander.png")
VA8KalitaTomas = img("faces/VA8KalitaTomas.png")
VA8KrobotAdam = img("faces/VA8KrobotAdam.png")
VA8LemakovaHelena = img("faces/VA8LemakovaHelena.png")
VA8OndrejProkop = img("faces/VA8OndrejProkop.png")
VA8PelclVojtech = img("faces/VA8PelclVojtech.png")
VA8PracharSebastian = img("faces/VA8PracharSebastian.png")
VA8ProchazkaJonas = img("faces/VA8ProchazkaJonas.png")
VA8ProchazkaSimon = img("faces/VA8ProchazkaSimon.png")
VA8ProchazkovaMKlara = img("faces/VA8ProchazkovaMKlara.png")
VA8SolcMichal = img("faces/VA8SolcMichal.png")
VA8StolinFilip = img("faces/VA8StolinFilip.png")
VA8SvobodovaMartina = img("faces/VA8SvobodovaMartina.png")
VA8VacekOliver = img("faces/VA8VacekOliver.png")
VA8VohralikJonas = img("faces/VA8VohralikJonas.png")
VackovaCjVVEkonomie = img("faces/VackovaCjVVEkonomie.jpg")
VasiljevovaBiVV = img("faces/VasiljevovaBiVV.jpg")
VavraCjVV = img("faces/VavraCjVV.jpg")
VB6BurgetovaLucie = img("faces/VB6BurgetovaLucie.png")
VB6HerynkovaEma = img("faces/VB6HerynkovaEma.png")
VB6HodgkinsDaniel = img("faces/VB6HodgkinsDaniel.png")
VB6HomolaVilem = img("faces/VB6HomolaVilem.png")
VB6HosekFilip = img("faces/VB6HosekFilip.png")
VB6HrabalovaBarbora = img("faces/VB6HrabalovaBarbora.png")
VB6JuranovaEliska = img("faces/VB6JuranovaEliska.png")
VB6KestlKrystof = img("faces/VB6KestlKrystof.png")
VB6KolarVojtech = img("faces/VB6KolarVojtech.png")
VB6LachovaEvelina = img("faces/VB6LachovaEvelina.png")
VB6MacourkovaTereza = img("faces/VB6MacourkovaTereza.png")
VB6MokrosovaKarolina = img("faces/VB6MokrosovaKarolina.png")
VB6NovakovaTereza = img("faces/VB6NovakovaTereza.png")
VB6PavkaRostislav = img("faces/VB6PavkaRostislav.png")
VB6PavlikovaMarika = img("faces/VB6PavlikovaMarika.png")
VB6PerinaAdam = img("faces/VB6PerinaAdam.png")
VB6PhungKienGiang = img("faces/VB6PhungKienGiang.png")
VB6PospisilovaDenisa = img("faces/VB6PospisilovaDenisa.png")
VB6PovysilovaAdela = img("faces/VB6PovysilovaAdela.png")
VB6PracharovaKlara = img("faces/VB6PracharovaKlara.png")
VB6SajfrtovaKaterina = img("faces/VB6SajfrtovaKaterina.png")
VB6SiotovaKlara = img("faces/VB6SiotovaKlara.png")
VB6StefankovaBarbora = img("faces/VB6StefankovaBarbora.png")
VB6StoppenMatej = img("faces/VB6StoppenMatej.png")
VB6SzromkovaKlara = img("faces/VB6SzromkovaKlara.png")
VB6VyhnalkovaNella = img("faces/VB6VyhnalkovaNella.png")
VB6ZapletalovaMarketa = img("faces/VB6ZapletalovaMarketa.png")
VB6ZapletalovaSimona = img("faces/VB6ZapletalovaSimona.png")
VB6ZarovskyVit = img("faces/VB6ZarovskyVit.png")
VB6ZdrazilMarek = img("faces/VB6ZdrazilMarek.png")
VB6ZdrazilovaNela = img("faces/VB6ZdrazilovaNela.png")
VB8AlfamovaJulija = img("faces/VB8AlfamovaJulija.png")
VB8ArabcukDavid = img("faces/VB8ArabcukDavid.png")
VB8CechacekAdam = img("faces/VB8CechacekAdam.png")
VB8DobiasovaSara = img("faces/VB8DobiasovaSara.png")
VB8DolezalovaAnna = img("faces/VB8DolezalovaAnna.png")
VB8FlajsarJan = img("faces/VB8FlajsarJan.png")
VB8HolecovaAnna = img("faces/VB8HolecovaAnna.png")
VB8HorakovaBarbora = img("faces/VB8HorakovaBarbora.png")
VB8KaderkaAlfred = img("faces/VB8KaderkaAlfred.png")
VB8KauerovaKarolina = img("faces/VB8KauerovaKarolina.png")
VB8KaureovaKaterina = img("faces/VB8KaureovaKaterina.png")
VB8KovarovaKaterina = img("faces/VB8KovarovaKaterina.png")
VB8KrestynovaMichaela = img("faces/VB8KrestynovaMichaela.png")
VB8LlunuskyMax = img("faces/VB8LlunuskyMax.png")
VB8MitrengaMatyas = img("faces/VB8MitrengaMatyas.png")
VB8NezvalTadeas = img("faces/VB8NezvalTadeas.png")
VB8NohejlovaKaterina = img("faces/VB8NohejlovaKaterina.png")
VB8NovakovaEliska = img("faces/VB8NovakovaEliska.png")
VB8PucekMartin = img("faces/VB8PucekMartin.png")
VB8SlachtovaAdela = img("faces/VB8SlachtovaAdela.png")
VB8SlajsovaLeona = img("faces/VB8SlajsovaLeona.png")
VB8SolleRadovan = img("faces/VB8SolleRadovan.png")
VB8StefanuttovaKlara = img("faces/VB8StefanuttovaKlara.png")
VB8StepanekJakub = img("faces/VB8StepanekJakub.png")
VB8UrbanovaMonika = img("faces/VB8UrbanovaMonika.png")
VB8UvirovaAlzbeta = img("faces/VB8UvirovaAlzbeta.png")
VB8VyroubalovaEliska = img("faces/VB8VyroubalovaEliska.png")
VB8ZajcevDmitrij = img("faces/VB8ZajcevDmitrij.png")
VB8ZemanAntonin = img("faces/VB8ZemanAntonin.png")
VB8ZochvovaTereza = img("faces/VB8ZochvovaTereza.png")
VeselaCjNe = img("faces/VeselaCjNe.jpg")
VIA6BahounkovaTereza = img("faces/VIA6BahounkovaTereza.png")
VIA6BizovaLucie = img("faces/VIA6BizovaLucie.png")
VIA6BreznickyAntonin = img("faces/VIA6BreznickyAntonin.png")
VIA6CiseckaSandra = img("faces/VIA6CiseckaSandra.png")
VIA6DrtikSimon = img("faces/VIA6DrtikSimon.png")
VIA6FibigrJiri = img("faces/VIA6FibigrJiri.png")
VIA6ForetkovaZElizabeth = img("faces/VIA6ForetkovaZElizabeth.png")
VIA6HladikVaclav = img("faces/VIA6HladikVaclav.png")
VIA6HlousekPetr = img("faces/VIA6HlousekPetr.png")
VIA6HoncikovaNatalie = img("faces/VIA6HoncikovaNatalie.png")
VIA6KnichalOndrej = img("faces/VIA6KnichalOndrej.png")
VIA6KubickovaEva = img("faces/VIA6KubickovaEva.png")
VIA6KurfurstDavid = img("faces/VIA6KurfurstDavid.png")
VIA6LosovaAneta = img("faces/VIA6LosovaAneta.png")
VIA6PalascakovaMarika = img("faces/VIA6PalascakovaMarika.png")
VIA6PavelkaTomas = img("faces/VIA6PavelkaTomas.png")
VIA6PrikopovaEliska = img("faces/VIA6PrikopovaEliska.png")
VIA6SkrachovaViktorie = img("faces/VIA6SkrachovaViktorie.png")
VIA6SoldanMichal = img("faces/VIA6SoldanMichal.png")
VIA6TalafousovaHelena = img("faces/VIA6TalafousovaHelena.png")
VIA6ValkovMarketa = img("faces/VIA6ValkovMarketa.png")
VIA6VokalJonas = img("faces/VIA6VokalJonas.png")
VIA6VolmutFilip = img("faces/VIA6VolmutFilip.png")
VIA6ZalioMarketa = img("faces/VIA6ZalioMarketa.png")
VIA6ZatloukalovaMarie = img("faces/VIA6ZatloukalovaMarie.png")
VIA6ZdrazilCyril = img("faces/VIA6ZdrazilCyril.png")
VIA8BednarStepan = img("faces/VIA8BednarStepan.png")
VIA8CoufalovaAgata = img("faces/VIA8CoufalovaAgata.png")
VIA8DejlovaKristyna = img("faces/VIA8DejlovaKristyna.png")
VIA8DufkaVojtech = img("faces/VIA8DufkaVojtech.png")
VIA8GregurkovaNikola = img("faces/VIA8GregurkovaNikola.png")
VIA8HamrikovaVeronika = img("faces/VIA8HamrikovaVeronika.png")
VIA8KardasPavel = img("faces/VIA8KardasPavel.png")
VIA8KazimirKristian = img("faces/VIA8KazimirKristian.png")
VIA8KoisPavel = img("faces/VIA8KoisPavel.png")
VIA8KolarikJaromir = img("faces/VIA8KolarikJaromir.png")
VIA8KolarJan = img("faces/VIA8KolarJan.png")
VIA8KutinovaLucie = img("faces/VIA8KutinovaLucie.png")
VIA8KvapilovaJana = img("faces/VIA8KvapilovaJana.png")
VIA8MartiseekJiri = img("faces/VIA8MartiseekJiri.png")
VIA8MikulkaPavel = img("faces/VIA8MikulkaPavel.png")
VIA8NemravaJonas = img("faces/VIA8NemravaJonas.png")
VIA8NevrlaKristyna = img("faces/VIA8NevrlaKristyna.png")
VIA8OndrousekJakub = img("faces/VIA8OndrousekJakub.png")
VIA8PodivinskyTomas = img("faces/VIA8PodivinskyTomas.png")
VIA8SchillerDenis = img("faces/VIA8SchillerDenis.png")
VIA8SiedloczekSebestian = img("faces/VIA8SiedloczekSebestian.png")
VIA8SimacekSAdam = img("faces/VIA8SimacekSAdam.png")
VIA8StavelovaBeata = img("faces/VIA8StavelovaBeata.png")
VIA8SuchanekAdam = img("faces/VIA8SuchanekAdam.png")
VIA8TomankovaKristyna = img("faces/VIA8TomankovaKristyna.png")
VIA8VecerovaNikola = img("faces/VIA8VecerovaNikola.png")
VIA8VodickovaAdela = img("faces/VIA8VodickovaAdela.png")
VIB6BacikovaAdela = img("faces/VIB6BacikovaAdela.png")
VIB6BudikJiri = img("faces/VIB6BudikJiri.png")
VIB6CaskovaAlena = img("faces/VIB6CaskovaAlena.png")
VIB6CtvrtlikovaKlara = img("faces/VIB6CtvrtlikovaKlara.png")
VIB6DitmarovaGabriela = img("faces/VIB6DitmarovaGabriela.png")
VIB6EliasovaJana = img("faces/VIB6EliasovaJana.png")
VIB6GadburkovaKlara = img("faces/VIB6GadburkovaKlara.png")
VIB6HamplJan = img("faces/VIB6HamplJan.png")
VIB6HavranovaTerezie = img("faces/VIB6HavranovaTerezie.png")
VIB6HrabalikovaKaterina = img("faces/VIB6HrabalikovaKaterina.png")
VIB6HrbacMichal = img("faces/VIB6HrbacMichal.png")
VIB6JelinkovaMagda = img("faces/VIB6JelinkovaMagda.png")
VIB6KamidinovAdriania = img("faces/VIB6KamidinovAdriania.png")
VIB6KolarovaAnna = img("faces/VIB6KolarovaAnna.png")
VIB6KrusoftovaAnna = img("faces/VIB6KrusoftovaAnna.png")
VIB6MarackovaMichaela = img("faces/VIB6MarackovaMichaela.png")
VIB6MartinVelky = img("faces/VIB6MartinVelky.png")
VIB6MerhautovaAlena = img("faces/VIB6MerhautovaAlena.png")
VIB6NejeschlebaMatej = img("faces/VIB6NejeschlebaMatej.png")
VIB6PrchalovaTereza = img("faces/VIB6PrchalovaTereza.png")
VIB6SewaltTimothy = img("faces/VIB6SewaltTimothy.png")
VIB6SiskovaKlara = img("faces/VIB6SiskovaKlara.png")
VIB6SiskovaTereza = img("faces/VIB6SiskovaTereza.png")
VIB6SkolovaKlara = img("faces/VIB6SkolovaKlara.png")
VIB6SmatlakovaAnna = img("faces/VIB6SmatlakovaAnna.png")
VIB6SvobodovaBarbora = img("faces/VIB6SvobodovaBarbora.png")
VIB6VeceraOndrej = img("faces/VIB6VeceraOndrej.png")
VIIA8AmbruzovaKlara = img("faces/VIIA8AmbruzovaKlara.png")
VIIA8CoufalovaAnezka = img("faces/VIIA8CoufalovaAnezka.png")
VIIA8CoufalovaMarta = img("faces/VIIA8CoufalovaMarta.png")
VIIA8DolezalAlex = img("faces/VIIA8DolezalAlex.png")
VIIA8HaichlovaAneta = img("faces/VIIA8HaichlovaAneta.png")
VIIA8HermanPatrik = img("faces/VIIA8HermanPatrik.png")
VIIA8JakubcovaAnna = img("faces/VIIA8JakubcovaAnna.png")
VIIA8KlaskovaVanessa = img("faces/VIIA8KlaskovaVanessa.png")
VIIA8KlimovaNela = img("faces/VIIA8KlimovaNela.png")
VIIA8KoudelkovaAnna = img("faces/VIIA8KoudelkovaAnna.png")
VIIA8KrylovaKristyna = img("faces/VIIA8KrylovaKristyna.png")
VIIA8LexaMartin = img("faces/VIIA8LexaMartin.png")
VIIA8MilieDominik = img("faces/VIIA8MilieDominik.png")
VIIA8PeteraJaroslav = img("faces/VIIA8PeteraJaroslav.png")
VIIA8PlodkovaZuzana = img("faces/VIIA8PlodkovaZuzana.png")
VIIA8PluskalVojtech = img("faces/VIIA8PluskalVojtech.png")
VIIA8PriborskyPetr = img("faces/VIIA8PriborskyPetr.png")
VIIA8ProchazkaJosef = img("faces/VIIA8ProchazkaJosef.png")
VIIA8RudorferMartin = img("faces/VIIA8RudorferMartin.png")
VIIA8SalekMarek = img("faces/VIIA8SalekMarek.png")
VIIA8SarazinPJulien = img("faces/VIIA8SarazinPJulien.png")
VIIA8SikorovaAneta = img("faces/VIIA8SikorovaAneta.png")
VIIA8SkacelOndrej = img("faces/VIIA8SkacelOndrej.png")
VIIA8SmidovaKlara = img("faces/VIIA8SmidovaKlara.png")
VIIA8StekldyMartin = img("faces/VIIA8StekldyMartin.png")
VIIIA8BalusJan = img("faces/VIIIA8BalusJan.png")
VIIIA8BerankuViki = img("faces/VIIIA8BerankuViki.png")
VIIIA8BieleszovaMarie = img("faces/VIIIA8BieleszovaMarie.png")
VIIIA8BlechovaAnna = img("faces/VIIIA8BlechovaAnna.png")
VIIIA8BredburovaPavla = img("faces/VIIIA8BredburovaPavla.png")
VIIIA8BrundaMatej = img("faces/VIIIA8BrundaMatej.png")
VIIIA8DolezalovaLucie = img("faces/VIIIA8DolezalovaLucie.png")
VIIIA8FikaZdenek = img("faces/VIIIA8FikaZdenek.png")
VIIIA8FilipcikStepan = img("faces/VIIIA8FilipcikStepan.png")
VIIIA8FilkovaVendula = img("faces/VIIIA8FilkovaVendula.png")
VIIIA8GrohmannOndrej = img("faces/VIIIA8GrohmannOndrej.png")
VIIIA8HamrikVit = img("faces/VIIIA8HamrikVit.png")
VIIIA8HrabalMatej = img("faces/VIIIA8HrabalMatej.png")
VIIIA8JuraskovaTereza = img("faces/VIIIA8JuraskovaTereza.png")
VIIIA8KolarovaJudita = img("faces/VIIIA8KolarovaJudita.png")
VIIIA8KratochvilMartin = img("faces/VIIIA8KratochvilMartin.png")
VIIIA8KvapilJiri = img("faces/VIIIA8KvapilJiri.png")
VIIIA8MachacekMarek = img("faces/VIIIA8MachacekMarek.png")
VIIIA8MachacovaMonika = img("faces/VIIIA8MachacovaMonika.png")
VIIIA8MarkovaMichaela = img("faces/VIIIA8MarkovaMichaela.png")
VIIIA8PanakovaLeona = img("faces/VIIIA8PanakovaLeona.png")
VIIIA8PelakMatej = img("faces/VIIIA8PelakMatej.png")
VIIIA8RatajovaVendula = img("faces/VIIIA8RatajovaVendula.png")
VIIIA8StankovaSandra = img("faces/VIIIA8StankovaSandra.png")
VIIIA8SzaboVeronika = img("faces/VIIIA8SzaboVeronika.png")
VIIIA8UngrovaStepanka = img("faces/VIIIA8UngrovaStepanka.png")
VIIIA8ZochovaBarbora = img("faces/VIIIA8ZochovaBarbora.png")
VitamvasovaAj = img("faces/VitamvasovaAj.jpg")
VojtovicovaMaFyAj = img("faces/VojtovicovaMaFyAj.jpg")
ZabojovaBiCh = img("faces/ZabojovaBiCh.jpg")
ZajicovaCjNe = img("faces/ZajicovaCjNe.jpg")
ZarubovaMaCh = img("faces/ZarubovaMaCh.jpg")
ZatloukalovaVVRu = img("faces/ZatloukalovaVVRu.jpg")
known_face_encodings = [AbrahamovaTv, Adamikova2AjRuD, BednarikovaMaITV, BerankovaAjFr, BraunerChBi, CastellarSp, CechovaAj, ChromaTvZ, DanielTvZ, DohnalovaCjHv, DostalovaTv, DubovaNeCj, DvorskyAjD, FaberovaAjRu, FerencMaFy, FukaCjNe, GlosCjD, HajduMaAj, HajekBiCh, HamrikovaMaCh, HavranovaAj, HermanovaCjHvRu, HorvathSp, HubackovaCjD, IA4BerkovaAnna, IA4BilikovaAlzbeta, IA4BrstakovaJulie, IA4BubenickovaAneta, IA4BuczkovaBarbora, IA4ChmelikLukas, IA4DankovaKarolina, IA4GalnorJakub, IA4GjurgjealaKaona, IA4HalovaBarbora, IA4HimrMatej, IA4HodurovaKEliska, IA4JanalikTomas, IA4KostkaJan, IA4KoukalFrantisek, IA4KrejciMatyas, IA4LipkovaValerie, IA4LosikLeonard, IA4MachovaDagmar, IA4PolednaJan, IA4StavarskaLucie, IA4StechovaBarbora, IA4StejskalovaLinda, IA4VaculikPetr, IA4WestphalDavid, IA6BaresovaKlara, IA6BelohlavkovaMarie, IA6CapalovaKarolina, IA6FedorcoMarian, IA6FilousovaLena, IA6HorklovaKatka, IA6KlosovaMarie, IA6KvapilMichael, IA6LukasovaAdela, IA6MachStepan, IA6MaslikovaTereza, IA6NavratilJachym, IA6PridalMatej, IA6PtackovaEliska, IA6SimakStepan, IA6SouckovaSara, IA6SouckovaZdenka, IA6SouskovaEliska, IA6StarostovaTereza, IA6StybnarMarek, IA6SvobodaDavid, IA6UherJan, IA6ValekDan, IA6VrajovaJana, IA6VyroubalRadek, IA6WittmannovaJAnna, IA6ZelenkovaTereza, IA6ZemberovaDaniela, IA8AuxtovaLinda, IA8BartosJan, IA8BenesovaJohana, IA8BouchalovaKveta, IA8ChmelovaVendula, IA8CisarVojtech, IA8DostalJakub, IA8FilousovaAlzbeta, IA8GajdusekMiroslav, IA8GogolJMatyas, IA8GrassovaEla, IA8HalatovaVeronika, IA8HandlovaKaterina, IA8HarnosovaAlzbeta, IA8HulikovaAmelie, IA8IlleovaAdela, IA8JensDavid, IA8KmentovaMarie, IA8KornhonTomas, IA8KropacDavid, IA8LonicekMartin, IA8MaslikovaKarolina, IA8MohylovaLaura, IA8MuchovaJohana, IA8NavratilDaniel, IA8ProchazkaJan, IA8StefanuttovaAmalie, IA8SterbovaSDana, IA8TichyMaxmilian, IA8ZdrazilovaAKarolina, IB4ApplovaPavlina, IB4BacikZeyner, IB4HavlikMatyas, IB4HrancovaMarketa, IB4HrnkovaGita, IB4JarosMichael, IB4KalabisovaAnna, IB4KejklickovaTereza, IB4MachVKrystof, IB4MadrovaAdriana, IB4MalaLenka, IB4MykhailetsVadim, IB4PopelkaStepan, IB4PospisilovaZuzana, IB4PrincDaniel, IB4SalamonJan, IB4SittekJakub, IB4SkladanyLukas, IB4SkrontovaEliska, IB4SkurkovaAdela, IB4SpevakovaEva, IB4StojakovaLucie, IB4StolfovaNatalie, IB4TajovskaNikola, IB4VejmolovaKarolina, IB6BrodaJakub, IB6CventanovaKaterina, IB6FisaraDavid, IB6KonecnaLucie, IB6KonecnyVit, IB6KriegovaPavlina, IB6KrizAntonin, IB6KubelkaErik, IB6LejskovaAdela, IB6LosikovaLada, IB6MacickovaJana, IB6MiksikovaNatalie, IB6MikulovaBerenika, IB6NajerMarek, IB6NepovimovaLucie, IB6NovotnyOndrej, IB6PribylVojtech, IB6RobertsonTomas, IB6RybaFrantisek, IB6SedajovaSarka, IB6SobekTomas, IB6SohnelDavid, IB6StefanovaEma, IB6StrnadelMichael, IB6SyrovatkovaEliska, IB6UrbamkovaAnezka, IB6UtikalovaLLeontyna, IB6VohankovaKlara, IB6ZborilovaSara, IB8BrundaMikulas, IB8BurdaJan, IB8ChrasteckyJan, IB8DoubalovaJarmila, IB8FischerOndrej, IB8GastaPetr, IB8IloemezueBeaAdachi, IB8KlimcakRichard, IB8KonecnaElla, IB8KubickovaSofire, IB8KubikJachym, IB8LacovaKristina, IB8LinekOndrej, IB8MachacovaEdita, IB8MorbicrovaAdela, IB8NgoTuongVan, IB8OndrouskovaTereza, IB8OpavskyVit, IB8PeterovaMichaela, IB8PiechDaniel, IB8RaabovaIva, IB8StoppenovaJulie, IB8TisovskyMikulas, IB8UtikalovaNJustyna, IB8VelickyVaclav, IB8VodickovaKristyna, IB8ZavadilTomas, IB8ZdarilDaniel, IIA4AndršJan, IIA4BiskupovaSimona, IIA4BlumaJan, IIA4ChodurkovaAnna, IIA4ChytilovaKarolina, IIA4DrahotuskaAmalie, IIA4DvorskaVeronika, IIA4FrancakovaKarla, IIA4FrkalFIlip, IIA4FrumarovaAdela, IIA4HolikovaNatalie, IIA4HrabalovaKlara, IIA4HrbackovaKristyna, IIA4HrbatovaEva, IIA4HunovaDenisa, IIA4JancikovaLucie, IIA4JanecekJakub, IIA4KudybBenjamin, IIA4LekešMatyas, IIA4MatejJiri, IIA4MikulkaPetr, IIA4NemecJakub, IIA4PekarJakub, IIA4SaladakTobias, IIA4SevernakovaVeronika, IIA4SmetakMarek, IIA4ZymovaAneta, IIA6BazgerovaEllen, IIA6DolezalovaElla, IIA6DracJan, IIA6DreslerVaclva, IIA6FilipovaKarolina, IIA6FrybortovaElisa, IIA6HamalovaAlzbeta, IIA6HomolacovaDarina, IIA6HorakovaEma, IIA6HorvathMatus, IIA6KolousekMarek, IIA6KysucanovaMilena, IIA6LerchStepan, IIA6MaskovaEEmma, IIA6PavelkovaZuzana, IIA6PilchovaZuzana, IIA6PlesnikAdam, IIA6SvetlikovaEma, IIA6TranNguyenHongMai, IIA6VaclavikovaNicol, IIA6VitkovaAneta, IIA6VlkovaEliska, IIA6VrtalovaPetra, IIA6WiedermannovaEla, IIA6ZatloukalovaNela, IIA6ZeitlerSamuel, IIA6ZidkovaBarbora, IIA8BalnerJakub, IIA8CablikovaAnna, IIA8CernaStella, IIA8CoufalovaBerenika, IIA8DupalovaMichaela, IIA8HajekKrystof, IIA8HamplJonas, IIA8HebelkaEdward, IIA8HyzlovaKaterina, IIA8KrumniklMartin, IIA8KuceraMiroslav, IIA8LokocMartin, IIA8MisurcovaMarie, IIA8OklestkovaZuzana, IIA8PerneckaAnna, IIA8PilkovaMagdalena, IIA8PospisilovaAnna, IIA8ProtivanekVojtech, IIA8SasinkaJaromir, IIA8SeckarovaVeronika, IIA8SlukaOndrej, IIA8SmerekFrantisek, IIA8SrovnalikovaSofie, IIA8TomankovaMahulena, IIA8UlicnyTOldrich, IIA8VaclavikovaAnna, IIA8VevodovaSofie, IIA8ZubakSamuel, IIB4CernyMichael, IIB4FrantikMichael, IIB4HajkovaNela, IIB4HawigerStepan, IIB4HlusiZaneta, IIB4HulmanAlexander, IIB4KastilovaMichaela, IIB4LatalovaAgata, IIB4LiskovaNatalie, IIB4LondaDavid, IIB4MachasTomas, IIB4MaderkovaTereza, IIB4MichalcovaMonika, IIB4PospisilAdam, IIB4RuzickovaJulie, IIB4SadilovaAneta, IIB4SalkovaJitka, IIB4SedlackovaKaterina, IIB4SemianovaVeronika, IIB4SirokaTereza, IIB4SkacelMatej, IIB4SnajdarRadek, IIB4SpacekVojtech, IIB4StrizJan, IIB4ZemanekJan, IIB6BuchtikJan, IIB6FoukalovaNela, IIB6FryblikovaDominika, IIB6FrysakovaKristyna, IIB6HavlikovaSara, IIB6HefkovaNela, IIB6HermanovskaKLinda, IIB6KadlecFilip, IIB6KafetsioisNikiforos, IIB6KlobouckovaAdela, IIB6KlvackovaEma, IIB6KrumniklovaDora, IIB6LabancovaBarbora, IIB6MezlovaAnezka, IIB6MichnaMarek, IIB6NedomaOndrej, IIB6NemravaStepan, IIB6NguyenovaHamy, IIB6OvacacikovaLucie, IIB6QuinnSophieEllen, IIB6SimonikovaSara, IIB6SinclovaAnna, IIB6StepanekJaroslav, IIB6StrakovaEma, IIB6TonnerovaENatalie, IIB6VyskupSamuel, IIC6BicLukas, IIC6BodnarVilem, IIC6HautlerPatrik, IIC6HradilJan, IIC6JanicekMatyas, IIC6KorcovaHana, IIC6KunstRichard, IIC6KyselyMartin, IIC6LabounkovaKlara, IIC6PavlikMartin, IIC6PechovaLucie, IIC6PerinovaNikol, IIC6PhanThiNhuMai, IIC6RajnochDavid, IIC6SiskovaMarketa, IIC6SmeralovaTereza, IIC6SmitalMartin, IIC6SofronieskiAlex, IIC6StastnyRIchard, IIC6SuchaTereza, IIC6SvrcekVojtech, IIC6TisonovaMarie, IIIA4BizonPavel, IIIA4BrezovskyDaniel, IIIA4DzurianovaLucie, IIIA4HavlovaKlara, IIIA4HorakovaNatalie, IIIA4HorakStepan, IIIA4JakobBenjamin, IIIA4JanackovaLucie, IIIA4JenikovaMonika, IIIA4JurtikovaJarmila, IIIA4KalvachMichal, IIIA4KnoflickovaJana, IIIA4KozlovskaElena, IIIA4LatalovaNikola, IIIA4LatalovaZuzana, IIIA4MajdiakJosef, IIIA4MonicovaKaterina, IIIA4MudrakVit, IIIA4NeoralovaZuzana, IIIA4NevecnaSarka, IIIA4NezhybovaKristyna, IIIA4PallaJiri, IIIA4PichovaAndrea, IIIA4RudykovaAlexandra, IIIA4StimplovaMarketa, IIIA4SuchankovaJasmina, IIIA4SvabenskaEliska, IIIA4TelickaTobias, IIIA4UtikalovaEliska, IIIA4VitoulovaTereza, IIIA4WeinlichovaNatalie, IIIA6AxmanPetr, IIIA6BuresADavid, IIIA6CermakJaroslav, IIIA6ChupikMichal, IIIA6HanikovaAdela, IIIA6HanzelkaFilip, IIIA6HeczkovaIzabela, IIIA6HorakovaValerie, IIIA6HulikovaVanessa, IIIA6JankuOto, IIIA6JavorikovaSara, IIIA6JenikovaHelena, IIIA6KanjanepokinSutheera, IIIA6KovarikovaHana, IIIA6KriklovaLucie, IIIA6KurfurstovaElena, IIIA6MarabetiRosalia, IIIA6MikesovaNela, IIIA6MohaplovaNikola, IIIA6NovotnyDavid, IIIA6OdstrcilovaBarbora, IIIA6SchwartzhoffovaMarie, IIIA6SkyvovaBarbora, IIIA6StaskovaMarie, IIIA6SvobodaDaniel, IIIA6VaclavikLukas, IIIA6ValentovaMarketa, IIIA6ZahradnickovaAnna, IIIA8BazantovaMagdalena, IIIA8BlahutovaEKarolina, IIIA8BodnarovaEma, IIIA8BubenicekDavid, IIIA8DejlMartin, IIIA8DrozdovaNela, IIIA8DudaBenjamin, IIIA8DvorakovaTereza, IIIA8FiserovaJana, IIIA8HoangovaAnh, IIIA8HolasekTomas, IIIA8HorakAlexandr, IIIA8HrabalNikola, IIIA8JanosikLukas, IIIA8KralovaIvana, IIIA8KratkyLukas, IIIA8KubikovaEliska, IIIA8KudlaRudolf, IIIA8KvapilovaTereza, IIIA8MutinaMarek, IIIA8MyskovaTereza, IIIA8NovakovaDaniela, IIIA8SlezarovaAnna, IIIA8SmekalovaLucie, IIIA8StavarskyRichard, IIIA8ValentovaVeronika, IIIA8VohralikovaJohana, IIIA8ZikmundovaAdela, IIIB4AssenzaSilvia, IIIB4BergmanVaclav, IIIB4ChudobovaJulie, IIIB4DornakovaLLeona, IIIB4DuskovaKristyna, IIIB4FlorianovaRadka, IIIB4HetovaBarbora, IIIB4JuchymivovaKarolina, IIIB4KikaSimon, IIIB4KucerovaAneta, IIIB4LavrincikovaLaura, IIIB4LyskovaKlaudie, IIIB4MiketovaAdela, IIIB4MiketovaAnna, IIIB4NovakOndrej, IIIB4NovakovaIveta, IIIB4PolednaOndrej, IIIB4RehacekAdam, IIIB4RosipalovaLucie, IIIB4SandrovaLucie, IIIB4SkrabalovaKristyna, IIIB4SlamencovaNikol, IIIB4SnoblovaAnna, IIIB4SpangerovaMarie, IIIB4UrbanDaniel, IIIB4VavrinTadeas, IIIB4VichovaEliska, IIIB4WagnerovaKlara, IIIB4ZborilovaKlara, IIIB4ZonaDavid, IIIB6BognarovaJulie, IIIB6CvetanRobert, IIIB6CvrckovaEliska, IIIB6HamplovaAnna, IIIB6HanykTomas, IIIB6HejdukovaLeona, IIIB6HrdlickaAdam, IIIB6JarosovaAdriana, IIIB6KorinkovaTana, IIIB6LatalovaNatalie, IIIB6MistaMatous, IIIB6NovotnaAgata, IIIB6PiechovaJulie, IIIB6PisoftovaEva, IIIB6PivodovaKaterina, IIIB6RuzickovaEma, IIIB6SedlakOndrej, IIIB6SeluckaBarbora, IIIB6SmekalMartin, IIIB6SowaJakub, IIIB6SpacekJakub, IIIB6SpertlikvoaVeronika, IIIB6TelcovaKlara, IIIB6ValentaAdam, IIIB6VranovaMarina, IIIB6VyslouzilovaElena, IIIB6ZizlavskaAmelie, IIIB8AmbrosMichael, IIIB8AxmanovaPavlina, IIIB8BuresEBenjamin, IIIB8CoufalovaNoemi, IIIB8DolezalovaHelena, IIIB8HavrlantSimon, IIIB8HimrJonas, IIIB8HockadaySMatthew, IIIB8HoudekJan, IIIB8JuraskovaAneta, IIIB8KlimkovaViola, IIIB8KolarJan, IIIB8KonecnyPetr, IIIB8LazarovaSofie, IIIB8MadrovaGabriela, IIIB8PaulickovaTereza, IIIB8PetrivalskyNil, IIIB8PolednovaSofie, IIIB8RatajovaTerezie, IIIB8SaradinMatej, IIIB8SimackovaMEmma, IIIB8SitovaHana, IIIB8SmutnaHana, IIIB8StefanovaAnna, IIIB8StyblovaTatiana, IIIB8TomeckovaAnna, IIIB8VaclavikovaAnna, IIIB8VeseckyJakub, IIIB8ZidkovaLinda, IVA4BrumarVaclav, IVA4CapecAmelia, IVA4CechovaMarie, IVA4ChrenkoMichael, IVA4DavidTomas, IVA4DramliukIlya, IVA4HalaxovaEmma, IVA4JakubecMilan, IVA4JasinkovaBarbora, IVA4KaplikovaLucie, IVA4KovarikovaEliska, IVA4KrytinarPavel, IVA4KubickovaEma, IVA4LolkovaKarolina, IVA4MalaValerie, IVA4MikulikovaSara, IVA4MorkovskaNikola, IVA4NovakovaMagdalena, IVA4PelisekMatej, IVA4PliskovaANikola, IVA4PolackovaAdela, IVA4PolisovaBarbora, IVA4RacekJakub, IVA4SalaquardaTadeas, IVA4SebanekEduard, IVA4SelicharovaLucie, IVA4SmekalovaBarbora, IVA4StrnadovaLucie, IVA4ZapletalovaZuzana, IVA6BalasovaNela, IVA6BergerViktorie, IVA6BirckaPetr, IVA6CepovaNatalie, IVA6DoubravaBoleslav, IVA6HejtmanovaLucie, IVA6HlavacovaPetra, IVA6JavorskyMartin, IVA6JelenkovaAlice, IVA6KorcanovaNatalie, IVA6KrocilovaVendula, IVA6KunstlerMarek, IVA6KyselyViktor, IVA6LatalovaLucie, IVA6LustigovaNellie, IVA6MeleckaAneta, IVA6PetrLovaLucie, IVA6PribylvoaNela, IVA6RichterovaJulie, IVA6SimkovaEmilie, IVA6SmatlakovaHana, IVA6SoukenikovaBarbora, IVA6SousekJan, IVA6StanekKrystof, IVA6StybnarovaLucie, IVA6TylsarovaAnna, IVA6VendelinFilip, IVA6ZlutirovaHelena, IVA8BouchalMarek, IVA8BrozdaAdam, IVA8CanibalFilip, IVA8CoufalovaJudita, IVA8DvorskyMichal, IVA8GeprtovaMartina, IVA8HalasVaclav, IVA8JuraMarek, IVA8KaresVit, IVA8KlimcakovaAnna, IVA8KoupilFlorian, IVA8KovarikVojtech, IVA8KurfurstAdam, IVA8LosseovaMarie, IVA8MohaplTomas, IVA8NavratilovaAmelie, IVA8NiemiecJiri, IVA8PippalNikolas, IVA8PospisilovaAnezka, IVA8ProchazkaJosef, IVA8ProchazkovaAnezka, IVA8PuskasJSamuel, IVA8SrotovaLucie, IVA8VanekKarel, IVA8VortelJakub, IVA8ZimovaSKarolina, IVB4BalnerovaAmalie, IVB4BenesKrystof, IVB4CharvatPetr, IVB4CtvrtlikovaElen, IVB4DrozdovaSvetlana, IVB4GalnorovaKaterina, IVB4HladisovaMarketa, IVB4JanosovaViktorie, IVB4KaiserovaAdela, IVB4KazinotaVojtěch, IVB4KnotkovaKaterina, IVB4KovalovaNikola, IVB4KovarikovaKlara, IVB4LiskovaJohana, IVB4MachalaJan, IVB4MensikMatej, IVB4PeleshkoKristyna, IVB4PospisilovaTereza, IVB4ReznickovaTereza, IVB4SanakJaroslav, IVB4SkopalovaLucie, IVB4SmatanovaKlara, IVB4SpitMartin, IVB4StruharovaGabriela, IVB4SvobodovaAneta, IVB4VachalovaAneta, IVB4VavrovaVendula, IVB4WunschovaKlara, IVB6BednarovaLudmila, IVB6BinarovaAdela, IVB6BombreovaJana, IVB6BurianovaIvana, IVB6CharvatovaKlara, IVB6DitmarovaValerie, IVB6DubovaTerezie, IVB6FinkovaVendula, IVB6ForalovaKaterina, IVB6GosovaEster, IVB6HartmannovaAlzbeta, IVB6HlaviznovaTereza, IVB6JuricekDavid, IVB6KlechPatrik, IVB6KosakovaEliska, IVB6KrumnikolvaEma, IVB6LosseJosef, IVB6NaspinskyDavid, IVB6NepsinskyDavid, IVB6SkopalovaAdela, IVB6SlotaVojtech, IVB6StancovaKamila, IVB6StastnaKarolina, IVB6StrnadovaKamila, IVB6UtikalovaLValentyna, IVB6VolmutJakub, IVB6VymazalTomas, IVB6ZaludaKrystof, IVB6ZamecnikovaElen, IVB6ZborilovaPavla, IVC4ApplHynek, IVC4DohnalJan, IVC4HatalovaMarketa, IVC4HenklovaEliska, IVC4KaplovaKarolina, IVC4LustigovaSophia, IVC4PodivinskyAdam, IVC4PrichystalKarlos, IVC4PrichystalovaMartina, IVC4PrincovaElizabeth, IVC4PsotkaVojtech, IVC4SandorJaromir, IVC4SanovecAdam, IVC4SpurnaEliska, IVC4StanoLukas, IVC4TajovskaKaterina, IVC4UtikalovaKarolina, IVC4VaculaAdam, IVC4VeselskaAnna, IVC4VykopalPavel, IVC4VysoudilovaVendula, IVC4ZdarilJakub, IVC4ZinkovaAneta, JanickovaAjCj, JonesAj, JurikTvZ, KalandrovaCjOv, KnapekAjSp, KonecnaNeCj, KostkovaMaCh, KovarovaMaCh, KralovaAj, KrcovaMaZ, KrejcirovaSp, KrejcirTvZ, KrizovaMaFy, KvapilMaFyHv, LekesovaCjHv, LetakovaBiCh, MadrovaAj, MarkovaBiCh, MartinikovaNeHv, MasnyOvVv, McMullinAj, MenouskovaCjFr, MinarikMa, NavratilBiZ, NavratilovaAj, NezvalovaAjRuD, OndrakOvLat, PazderovaMaFy, PetrMaFy, PiechovaAj, PohanelMaZAjProjekty, PolednovaMaZ, PridalovaAjRu, PrzybylovaCjHv, PuskarovaNeCj, RehulkaBiCh, RichterkovaMaFy, SedlackovaCjFr, SeverovaMaIVT, SladecekCjAj, SoubustovaNeRu, StanecSp, StepanovIVT, StranskaFy, StudnickaMaIVT, SuchankovaAj, SykorovaAjD, TeplyAjTv, UrbaskovaMaZ, VA6AujeskaKaterina, VA6CernoskovaLinda, VA6ChudzikJan, VA6DolezelovaAndrea, VA6GrablPatrik, VA6GunkovaEliska, VA6HarastovaEliska, VA6HautlerovaEliska, VA6KralovaSara, VA6KrejciMagdalena, VA6KrupickovaKamila, VA6LejskovaAdina, VA6MrazkovaAdela, VA6NavratilPetr, VA6OpletalovaSElisa, VA6PalouskovaTereza, VA6PavlickovaATerezie, VA6PavlickovaMonika, VA6PepekPospisil, VA6PolasekMartin, VA6PtasnikSimon, VA6PuckovaOlga, VA6RoubalikOta, VA6ValouskkovaMiroslavav, VA6VasickovaVendula, VA6ZakovaAnna, VA6ZavodnikovaBerenika, VA8BrundaAlbert, VA8DudovaAnezka, VA8DvorakovaVera, VA8GorcaRafael, VA8HavrlantovaElen, VA8HockadayMHana, VA8HrosovaMartina, VA8HudcovaNatalie, VA8JirovskyTomas, VA8JuklAlexander, VA8KalitaTomas, VA8KrobotAdam, VA8LemakovaHelena, VA8OndrejProkop, VA8PelclVojtech, VA8PracharSebastian, VA8ProchazkaJonas, VA8ProchazkaSimon, VA8ProchazkovaMKlara, VA8SolcMichal, VA8StolinFilip, VA8SvobodovaMartina, VA8VacekOliver, VA8VohralikJonas, VackovaCjVVEkonomie, VasiljevovaBiVV, VavraCjVV, VB6BurgetovaLucie, VB6HerynkovaEma, VB6HodgkinsDaniel, VB6HomolaVilem, VB6HosekFilip, VB6HrabalovaBarbora, VB6JuranovaEliska, VB6KestlKrystof, VB6KolarVojtech, VB6LachovaEvelina, VB6MacourkovaTereza, VB6MokrosovaKarolina, VB6NovakovaTereza, VB6PavkaRostislav, VB6PavlikovaMarika, VB6PerinaAdam, VB6PhungKienGiang, VB6PospisilovaDenisa, VB6PovysilovaAdela, VB6PracharovaKlara, VB6SajfrtovaKaterina, VB6SiotovaKlara, VB6StefankovaBarbora, VB6StoppenMatej, VB6SzromkovaKlara, VB6VyhnalkovaNella, VB6ZapletalovaMarketa, VB6ZapletalovaSimona, VB6ZarovskyVit, VB6ZdrazilMarek, VB6ZdrazilovaNela, VB8AlfamovaJulija, VB8ArabcukDavid, VB8CechacekAdam, VB8DobiasovaSara, VB8DolezalovaAnna, VB8FlajsarJan, VB8HolecovaAnna, VB8HorakovaBarbora, VB8KaderkaAlfred, VB8KauerovaKarolina, VB8KaureovaKaterina, VB8KovarovaKaterina, VB8KrestynovaMichaela, VB8LlunuskyMax, VB8MitrengaMatyas, VB8NezvalTadeas, VB8NohejlovaKaterina, VB8NovakovaEliska, VB8PucekMartin, VB8SlachtovaAdela, VB8SlajsovaLeona, VB8SolleRadovan, VB8StefanuttovaKlara, VB8StepanekJakub, VB8UrbanovaMonika, VB8UvirovaAlzbeta, VB8VyroubalovaEliska, VB8ZajcevDmitrij, VB8ZemanAntonin, VB8ZochvovaTereza, VeselaCjNe, VIA6BahounkovaTereza, VIA6BizovaLucie, VIA6BreznickyAntonin, VIA6CiseckaSandra, VIA6DrtikSimon, VIA6FibigrJiri, VIA6ForetkovaZElizabeth, VIA6HladikVaclav, VIA6HlousekPetr, VIA6HoncikovaNatalie, VIA6KnichalOndrej, VIA6KubickovaEva, VIA6KurfurstDavid, VIA6LosovaAneta, VIA6PalascakovaMarika, VIA6PavelkaTomas, VIA6PrikopovaEliska, VIA6SkrachovaViktorie, VIA6SoldanMichal, VIA6TalafousovaHelena, VIA6ValkovMarketa, VIA6VokalJonas, VIA6VolmutFilip, VIA6ZalioMarketa, VIA6ZatloukalovaMarie, VIA6ZdrazilCyril, VIA8BednarStepan, VIA8CoufalovaAgata, VIA8DejlovaKristyna, VIA8DufkaVojtech, VIA8GregurkovaNikola, VIA8HamrikovaVeronika, VIA8KardasPavel, VIA8KazimirKristian, VIA8KoisPavel, VIA8KolarikJaromir, VIA8KolarJan, VIA8KutinovaLucie, VIA8KvapilovaJana, VIA8MartiseekJiri, VIA8MikulkaPavel, VIA8NemravaJonas, VIA8NevrlaKristyna, VIA8OndrousekJakub, VIA8PodivinskyTomas, VIA8SchillerDenis, VIA8SiedloczekSebestian, VIA8SimacekSAdam, VIA8StavelovaBeata, VIA8SuchanekAdam, VIA8TomankovaKristyna, VIA8VecerovaNikola, VIA8VodickovaAdela, VIB6BacikovaAdela, VIB6BudikJiri, VIB6CaskovaAlena, VIB6CtvrtlikovaKlara, VIB6DitmarovaGabriela, VIB6EliasovaJana, VIB6GadburkovaKlara, VIB6HamplJan, VIB6HavranovaTerezie, VIB6HrabalikovaKaterina, VIB6HrbacMichal, VIB6JelinkovaMagda, VIB6KamidinovAdriania, VIB6KolarovaAnna, VIB6KrusoftovaAnna, VIB6MarackovaMichaela, VIB6MartinVelky, VIB6MerhautovaAlena, VIB6NejeschlebaMatej, VIB6PrchalovaTereza, VIB6SewaltTimothy, VIB6SiskovaKlara, VIB6SiskovaTereza, VIB6SkolovaKlara, VIB6SmatlakovaAnna, VIB6SvobodovaBarbora, VIB6VeceraOndrej, VIIA8AmbruzovaKlara, VIIA8CoufalovaAnezka, VIIA8CoufalovaMarta, VIIA8DolezalAlex, VIIA8HaichlovaAneta, VIIA8HermanPatrik, VIIA8JakubcovaAnna, VIIA8KlaskovaVanessa, VIIA8KlimovaNela, VIIA8KoudelkovaAnna, VIIA8KrylovaKristyna, VIIA8LexaMartin, VIIA8MilieDominik, VIIA8PeteraJaroslav, VIIA8PlodkovaZuzana, VIIA8PluskalVojtech, VIIA8PriborskyPetr, VIIA8ProchazkaJosef, VIIA8RudorferMartin, VIIA8SalekMarek, VIIA8SarazinPJulien, VIIA8SikorovaAneta, VIIA8SkacelOndrej, VIIA8SmidovaKlara, VIIA8StekldyMartin, VIIIA8BalusJan, VIIIA8BerankuViki, VIIIA8BieleszovaMarie, VIIIA8BlechovaAnna, VIIIA8BredburovaPavla, VIIIA8BrundaMatej, VIIIA8DolezalovaLucie, VIIIA8FikaZdenek, VIIIA8FilipcikStepan, VIIIA8FilkovaVendula, VIIIA8GrohmannOndrej, VIIIA8HamrikVit, VIIIA8HrabalMatej, VIIIA8JuraskovaTereza, VIIIA8KolarovaJudita, VIIIA8KratochvilMartin, VIIIA8KvapilJiri, VIIIA8MachacekMarek, VIIIA8MachacovaMonika, VIIIA8MarkovaMichaela, VIIIA8PanakovaLeona, VIIIA8PelakMatej, VIIIA8RatajovaVendula, VIIIA8StankovaSandra, VIIIA8SzaboVeronika, VIIIA8UngrovaStepanka, VIIIA8ZochovaBarbora, VitamvasovaAj, VojtovicovaMaFyAj, ZabojovaBiCh, ZajicovaCjNe, ZarubovaMaCh, ZatloukalovaVVRu]
known_face_names = ['AbrahamovaTv', 'Adamikova2AjRuD', 'BednarikovaMaITV', 'BerankovaAjFr', 'BraunerChBi', 'CastellarSp', 'CechovaAj', 'ChromaTvZ', 'DanielTvZ', 'DohnalovaCjHv', 'DostalovaTv', 'DubovaNeCj', 'DvorskyAjD', 'FaberovaAjRu', 'FerencMaFy', 'FukaCjNe', 'GlosCjD', 'HajduMaAj', 'HajekBiCh', 'HamrikovaMaCh', 'HavranovaAj', 'HermanovaCjHvRu', 'HorvathSp', 'HubackovaCjD', 'IA4BerkovaAnna', 'IA4BilikovaAlzbeta', 'IA4BrstakovaJulie', 'IA4BubenickovaAneta', 'IA4BuczkovaBarbora', 'IA4ChmelikLukas', 'IA4DankovaKarolina', 'IA4GalnorJakub', 'IA4GjurgjealaKaona', 'IA4HalovaBarbora', 'IA4HimrMatej', 'IA4HodurovaKEliska', 'IA4JanalikTomas', 'IA4KostkaJan', 'IA4KoukalFrantisek', 'IA4KrejciMatyas', 'IA4LipkovaValerie', 'IA4LosikLeonard', 'IA4MachovaDagmar', 'IA4PolednaJan', 'IA4StavarskaLucie', 'IA4StechovaBarbora', 'IA4StejskalovaLinda', 'IA4VaculikPetr', 'IA4WestphalDavid', 'IA6BaresovaKlara', 'IA6BelohlavkovaMarie', 'IA6CapalovaKarolina', 'IA6FedorcoMarian', 'IA6FilousovaLena', 'IA6HorklovaKatka', 'IA6KlosovaMarie', 'IA6KvapilMichael', 'IA6LukasovaAdela', 'IA6MachStepan', 'IA6MaslikovaTereza', 'IA6NavratilJachym', 'IA6PridalMatej', 'IA6PtackovaEliska', 'IA6SimakStepan', 'IA6SouckovaSara', 'IA6SouckovaZdenka', 'IA6SouskovaEliska', 'IA6StarostovaTereza', 'IA6StybnarMarek', 'IA6SvobodaDavid', 'IA6UherJan', 'IA6ValekDan', 'IA6VrajovaJana', 'IA6VyroubalRadek', 'IA6WittmannovaJAnna', 'IA6ZelenkovaTereza', 'IA6ZemberovaDaniela', 'IA8AuxtovaLinda', 'IA8BartosJan', 'IA8BenesovaJohana', 'IA8BouchalovaKveta', 'IA8ChmelovaVendula', 'IA8CisarVojtech', 'IA8DostalJakub', 'IA8FilousovaAlzbeta', 'IA8GajdusekMiroslav', 'IA8GogolJMatyas', 'IA8GrassovaEla', 'IA8HalatovaVeronika', 'IA8HandlovaKaterina', 'IA8HarnosovaAlzbeta', 'IA8HulikovaAmelie', 'IA8IlleovaAdela', 'IA8JensDavid', 'IA8KmentovaMarie', 'IA8KornhonTomas', 'IA8KropacDavid', 'IA8LonicekMartin', 'IA8MaslikovaKarolina', 'IA8MohylovaLaura', 'IA8MuchovaJohana', 'IA8NavratilDaniel', 'IA8ProchazkaJan', 'IA8StefanuttovaAmalie', 'IA8SterbovaSDana', 'IA8TichyMaxmilian', 'IA8ZdrazilovaAKarolina', 'IB4ApplovaPavlina', 'IB4BacikZeyner', 'IB4HavlikMatyas', 'IB4HrancovaMarketa', 'IB4HrnkovaGita', 'IB4JarosMichael', 'IB4KalabisovaAnna', 'IB4KejklickovaTereza', 'IB4MachVKrystof', 'IB4MadrovaAdriana', 'IB4MalaLenka', 'IB4MykhailetsVadim', 'IB4PopelkaStepan', 'IB4PospisilovaZuzana', 'IB4PrincDaniel', 'IB4SalamonJan', 'IB4SittekJakub', 'IB4SkladanyLukas', 'IB4SkrontovaEliska', 'IB4SkurkovaAdela', 'IB4SpevakovaEva', 'IB4StojakovaLucie', 'IB4StolfovaNatalie', 'IB4TajovskaNikola', 'IB4VejmolovaKarolina', 'IB6BrodaJakub', 'IB6CventanovaKaterina', 'IB6FisaraDavid', 'IB6KonecnaLucie', 'IB6KonecnyVit', 'IB6KriegovaPavlina', 'IB6KrizAntonin', 'IB6KubelkaErik', 'IB6LejskovaAdela', 'IB6LosikovaLada', 'IB6MacickovaJana', 'IB6MiksikovaNatalie', 'IB6MikulovaBerenika', 'IB6NajerMarek', 'IB6NepovimovaLucie', 'IB6NovotnyOndrej', 'IB6PribylVojtech', 'IB6RobertsonTomas', 'IB6RybaFrantisek', 'IB6SedajovaSarka', 'IB6SobekTomas', 'IB6SohnelDavid', 'IB6StefanovaEma', 'IB6StrnadelMichael', 'IB6SyrovatkovaEliska', 'IB6UrbamkovaAnezka', 'IB6UtikalovaLLeontyna', 'IB6VohankovaKlara', 'IB6ZborilovaSara', 'IB8BrundaMikulas', 'IB8BurdaJan', 'IB8ChrasteckyJan', 'IB8DoubalovaJarmila', 'IB8FischerOndrej', 'IB8GastaPetr', 'IB8IloemezueBeaAdachi', 'IB8KlimcakRichard', 'IB8KonecnaElla', 'IB8KubickovaSofire', 'IB8KubikJachym', 'IB8LacovaKristina', 'IB8LinekOndrej', 'IB8MachacovaEdita', 'IB8MorbicrovaAdela', 'IB8NgoTuongVan', 'IB8OndrouskovaTereza', 'IB8OpavskyVit', 'IB8PeterovaMichaela', 'IB8PiechDaniel', 'IB8RaabovaIva', 'IB8StoppenovaJulie', 'IB8TisovskyMikulas', 'IB8UtikalovaNJustyna', 'IB8VelickyVaclav', 'IB8VodickovaKristyna', 'IB8ZavadilTomas', 'IB8ZdarilDaniel', 'IIA4AndršJan', 'IIA4BiskupovaSimona', 'IIA4BlumaJan', 'IIA4ChodurkovaAnna', 'IIA4ChytilovaKarolina', 'IIA4DrahotuskaAmalie', 'IIA4DvorskaVeronika', 'IIA4FrancakovaKarla', 'IIA4FrkalFIlip', 'IIA4FrumarovaAdela', 'IIA4HolikovaNatalie', 'IIA4HrabalovaKlara', 'IIA4HrbackovaKristyna', 'IIA4HrbatovaEva', 'IIA4HunovaDenisa', 'IIA4JancikovaLucie', 'IIA4JanecekJakub', 'IIA4KudybBenjamin', 'IIA4LekešMatyas', 'IIA4MatejJiri', 'IIA4MikulkaPetr', 'IIA4NemecJakub', 'IIA4PekarJakub', 'IIA4SaladakTobias', 'IIA4SevernakovaVeronika', 'IIA4SmetakMarek', 'IIA4ZymovaAneta', 'IIA6BazgerovaEllen', 'IIA6DolezalovaElla', 'IIA6DracJan', 'IIA6DreslerVaclva', 'IIA6FilipovaKarolina', 'IIA6FrybortovaElisa', 'IIA6HamalovaAlzbeta', 'IIA6HomolacovaDarina', 'IIA6HorakovaEma', 'IIA6HorvathMatus', 'IIA6KolousekMarek', 'IIA6KysucanovaMilena', 'IIA6LerchStepan', 'IIA6MaskovaEEmma', 'IIA6PavelkovaZuzana', 'IIA6PilchovaZuzana', 'IIA6PlesnikAdam', 'IIA6SvetlikovaEma', 'IIA6TranNguyenHongMai', 'IIA6VaclavikovaNicol', 'IIA6VitkovaAneta', 'IIA6VlkovaEliska', 'IIA6VrtalovaPetra', 'IIA6WiedermannovaEla', 'IIA6ZatloukalovaNela', 'IIA6ZeitlerSamuel', 'IIA6ZidkovaBarbora', 'IIA8BalnerJakub', 'IIA8CablikovaAnna', 'IIA8CernaStella', 'IIA8CoufalovaBerenika', 'IIA8DupalovaMichaela', 'IIA8HajekKrystof', 'IIA8HamplJonas', 'IIA8HebelkaEdward', 'IIA8HyzlovaKaterina', 'IIA8KrumniklMartin', 'IIA8KuceraMiroslav', 'IIA8LokocMartin', 'IIA8MisurcovaMarie', 'IIA8OklestkovaZuzana', 'IIA8PerneckaAnna', 'IIA8PilkovaMagdalena', 'IIA8PospisilovaAnna', 'IIA8ProtivanekVojtech', 'IIA8SasinkaJaromir', 'IIA8SeckarovaVeronika', 'IIA8SlukaOndrej', 'IIA8SmerekFrantisek', 'IIA8SrovnalikovaSofie', 'IIA8TomankovaMahulena', 'IIA8UlicnyTOldrich', 'IIA8VaclavikovaAnna', 'IIA8VevodovaSofie', 'IIA8ZubakSamuel', 'IIB4CernyMichael', 'IIB4FrantikMichael', 'IIB4HajkovaNela', 'IIB4HawigerStepan', 'IIB4HlusiZaneta', 'IIB4HulmanAlexander', 'IIB4KastilovaMichaela', 'IIB4LatalovaAgata', 'IIB4LiskovaNatalie', 'IIB4LondaDavid', 'IIB4MachasTomas', 'IIB4MaderkovaTereza', 'IIB4MichalcovaMonika', 'IIB4PospisilAdam', 'IIB4RuzickovaJulie', 'IIB4SadilovaAneta', 'IIB4SalkovaJitka', 'IIB4SedlackovaKaterina', 'IIB4SemianovaVeronika', 'IIB4SirokaTereza', 'IIB4SkacelMatej', 'IIB4SnajdarRadek', 'IIB4SpacekVojtech', 'IIB4StrizJan', 'IIB4ZemanekJan', 'IIB6BuchtikJan', 'IIB6FoukalovaNela', 'IIB6FryblikovaDominika', 'IIB6FrysakovaKristyna', 'IIB6HavlikovaSara', 'IIB6HefkovaNela', 'IIB6HermanovskaKLinda', 'IIB6KadlecFilip', 'IIB6KafetsioisNikiforos', 'IIB6KlobouckovaAdela', 'IIB6KlvackovaEma', 'IIB6KrumniklovaDora', 'IIB6LabancovaBarbora', 'IIB6MezlovaAnezka', 'IIB6MichnaMarek', 'IIB6NedomaOndrej', 'IIB6NemravaStepan', 'IIB6NguyenovaHamy', 'IIB6OvacacikovaLucie', 'IIB6QuinnSophieEllen', 'IIB6SimonikovaSara', 'IIB6SinclovaAnna', 'IIB6StepanekJaroslav', 'IIB6StrakovaEma', 'IIB6TonnerovaENatalie', 'IIB6VyskupSamuel', 'IIC6BicLukas', 'IIC6BodnarVilem', 'IIC6HautlerPatrik', 'IIC6HradilJan', 'IIC6JanicekMatyas', 'IIC6KorcovaHana', 'IIC6KunstRichard', 'IIC6KyselyMartin', 'IIC6LabounkovaKlara', 'IIC6PavlikMartin', 'IIC6PechovaLucie', 'IIC6PerinovaNikol', 'IIC6PhanThiNhuMai', 'IIC6RajnochDavid', 'IIC6SiskovaMarketa', 'IIC6SmeralovaTereza', 'IIC6SmitalMartin', 'IIC6SofronieskiAlex', 'IIC6StastnyRIchard', 'IIC6SuchaTereza', 'IIC6SvrcekVojtech', 'IIC6TisonovaMarie', 'IIIA4BizonPavel', 'IIIA4BrezovskyDaniel', 'IIIA4DzurianovaLucie', 'IIIA4HavlovaKlara', 'IIIA4HorakovaNatalie', 'IIIA4HorakStepan', 'IIIA4JakobBenjamin', 'IIIA4JanackovaLucie', 'IIIA4JenikovaMonika', 'IIIA4JurtikovaJarmila', 'IIIA4KalvachMichal', 'IIIA4KnoflickovaJana', 'IIIA4KozlovskaElena', 'IIIA4LatalovaNikola', 'IIIA4LatalovaZuzana', 'IIIA4MajdiakJosef', 'IIIA4MonicovaKaterina', 'IIIA4MudrakVit', 'IIIA4NeoralovaZuzana', 'IIIA4NevecnaSarka', 'IIIA4NezhybovaKristyna', 'IIIA4PallaJiri', 'IIIA4PichovaAndrea', 'IIIA4RudykovaAlexandra', 'IIIA4StimplovaMarketa', 'IIIA4SuchankovaJasmina', 'IIIA4SvabenskaEliska', 'IIIA4TelickaTobias', 'IIIA4UtikalovaEliska', 'IIIA4VitoulovaTereza', 'IIIA4WeinlichovaNatalie', 'IIIA6AxmanPetr', 'IIIA6BuresADavid', 'IIIA6CermakJaroslav', 'IIIA6ChupikMichal', 'IIIA6HanikovaAdela', 'IIIA6HanzelkaFilip', 'IIIA6HeczkovaIzabela', 'IIIA6HorakovaValerie', 'IIIA6HulikovaVanessa', 'IIIA6JankuOto', 'IIIA6JavorikovaSara', 'IIIA6JenikovaHelena', 'IIIA6KanjanepokinSutheera', 'IIIA6KovarikovaHana', 'IIIA6KriklovaLucie', 'IIIA6KurfurstovaElena', 'IIIA6MarabetiRosalia', 'IIIA6MikesovaNela', 'IIIA6MohaplovaNikola', 'IIIA6NovotnyDavid', 'IIIA6OdstrcilovaBarbora', 'IIIA6SchwartzhoffovaMarie', 'IIIA6SkyvovaBarbora', 'IIIA6StaskovaMarie', 'IIIA6SvobodaDaniel', 'IIIA6VaclavikLukas', 'IIIA6ValentovaMarketa', 'IIIA6ZahradnickovaAnna', 'IIIA8BazantovaMagdalena', 'IIIA8BlahutovaEKarolina', 'IIIA8BodnarovaEma', 'IIIA8BubenicekDavid', 'IIIA8DejlMartin', 'IIIA8DrozdovaNela', 'IIIA8DudaBenjamin', 'IIIA8DvorakovaTereza', 'IIIA8FiserovaJana', 'IIIA8HoangovaAnh', 'IIIA8HolasekTomas', 'IIIA8HorakAlexandr', 'IIIA8HrabalNikola', 'IIIA8JanosikLukas', 'IIIA8KralovaIvana', 'IIIA8KratkyLukas', 'IIIA8KubikovaEliska', 'IIIA8KudlaRudolf', 'IIIA8KvapilovaTereza', 'IIIA8MutinaMarek', 'IIIA8MyskovaTereza', 'IIIA8NovakovaDaniela', 'IIIA8SlezarovaAnna', 'IIIA8SmekalovaLucie', 'IIIA8StavarskyRichard', 'IIIA8ValentovaVeronika', 'IIIA8VohralikovaJohana', 'IIIA8ZikmundovaAdela', 'IIIB4AssenzaSilvia', 'IIIB4BergmanVaclav', 'IIIB4ChudobovaJulie', 'IIIB4DornakovaLLeona', 'IIIB4DuskovaKristyna', 'IIIB4FlorianovaRadka', 'IIIB4HetovaBarbora', 'IIIB4JuchymivovaKarolina', 'IIIB4KikaSimon', 'IIIB4KucerovaAneta', 'IIIB4LavrincikovaLaura', 'IIIB4LyskovaKlaudie', 'IIIB4MiketovaAdela', 'IIIB4MiketovaAnna', 'IIIB4NovakOndrej', 'IIIB4NovakovaIveta', 'IIIB4PolednaOndrej', 'IIIB4RehacekAdam', 'IIIB4RosipalovaLucie', 'IIIB4SandrovaLucie', 'IIIB4SkrabalovaKristyna', 'IIIB4SlamencovaNikol', 'IIIB4SnoblovaAnna', 'IIIB4SpangerovaMarie', 'IIIB4UrbanDaniel', 'IIIB4VavrinTadeas', 'IIIB4VichovaEliska', 'IIIB4WagnerovaKlara', 'IIIB4ZborilovaKlara', 'IIIB4ZonaDavid', 'IIIB6BognarovaJulie', 'IIIB6CvetanRobert', 'IIIB6CvrckovaEliska', 'IIIB6HamplovaAnna', 'IIIB6HanykTomas', 'IIIB6HejdukovaLeona', 'IIIB6HrdlickaAdam', 'IIIB6JarosovaAdriana', 'IIIB6KorinkovaTana', 'IIIB6LatalovaNatalie', 'IIIB6MistaMatous', 'IIIB6NovotnaAgata', 'IIIB6PiechovaJulie', 'IIIB6PisoftovaEva', 'IIIB6PivodovaKaterina', 'IIIB6RuzickovaEma', 'IIIB6SedlakOndrej', 'IIIB6SeluckaBarbora', 'IIIB6SmekalMartin', 'IIIB6SowaJakub', 'IIIB6SpacekJakub', 'IIIB6SpertlikvoaVeronika', 'IIIB6TelcovaKlara', 'IIIB6ValentaAdam', 'IIIB6VranovaMarina', 'IIIB6VyslouzilovaElena', 'IIIB6ZizlavskaAmelie', 'IIIB8AmbrosMichael', 'IIIB8AxmanovaPavlina', 'IIIB8BuresEBenjamin', 'IIIB8CoufalovaNoemi', 'IIIB8DolezalovaHelena', 'IIIB8HavrlantSimon', 'IIIB8HimrJonas', 'IIIB8HockadaySMatthew', 'IIIB8HoudekJan', 'IIIB8JuraskovaAneta', 'IIIB8KlimkovaViola', 'IIIB8KolarJan', 'IIIB8KonecnyPetr', 'IIIB8LazarovaSofie', 'IIIB8MadrovaGabriela', 'IIIB8PaulickovaTereza', 'IIIB8PetrivalskyNil', 'IIIB8PolednovaSofie', 'IIIB8RatajovaTerezie', 'IIIB8SaradinMatej', 'IIIB8SimackovaMEmma', 'IIIB8SitovaHana', 'IIIB8SmutnaHana', 'IIIB8StefanovaAnna', 'IIIB8StyblovaTatiana', 'IIIB8TomeckovaAnna', 'IIIB8VaclavikovaAnna', 'IIIB8VeseckyJakub', 'IIIB8ZidkovaLinda', 'IVA4BrumarVaclav', 'IVA4CapecAmelia', 'IVA4CechovaMarie', 'IVA4ChrenkoMichael', 'IVA4DavidTomas', 'IVA4DramliukIlya', 'IVA4HalaxovaEmma', 'IVA4JakubecMilan', 'IVA4JasinkovaBarbora', 'IVA4KaplikovaLucie', 'IVA4KovarikovaEliska', 'IVA4KrytinarPavel', 'IVA4KubickovaEma', 'IVA4LolkovaKarolina', 'IVA4MalaValerie', 'IVA4MikulikovaSara', 'IVA4MorkovskaNikola', 'IVA4NovakovaMagdalena', 'IVA4PelisekMatej', 'IVA4PliskovaANikola', 'IVA4PolackovaAdela', 'IVA4PolisovaBarbora', 'IVA4RacekJakub', 'IVA4SalaquardaTadeas', 'IVA4SebanekEduard', 'IVA4SelicharovaLucie', 'IVA4SmekalovaBarbora', 'IVA4StrnadovaLucie', 'IVA4ZapletalovaZuzana', 'IVA6BalasovaNela', 'IVA6BergerViktorie', 'IVA6BirckaPetr', 'IVA6CepovaNatalie', 'IVA6DoubravaBoleslav', 'IVA6HejtmanovaLucie', 'IVA6HlavacovaPetra', 'IVA6JavorskyMartin', 'IVA6JelenkovaAlice', 'IVA6KorcanovaNatalie', 'IVA6KrocilovaVendula', 'IVA6KunstlerMarek', 'IVA6KyselyViktor', 'IVA6LatalovaLucie', 'IVA6LustigovaNellie', 'IVA6MeleckaAneta', 'IVA6PetrLovaLucie', 'IVA6PribylvoaNela', 'IVA6RichterovaJulie', 'IVA6SimkovaEmilie', 'IVA6SmatlakovaHana', 'IVA6SoukenikovaBarbora', 'IVA6SousekJan', 'IVA6StanekKrystof', 'IVA6StybnarovaLucie', 'IVA6TylsarovaAnna', 'IVA6VendelinFilip', 'IVA6ZlutirovaHelena', 'IVA8BouchalMarek', 'IVA8BrozdaAdam', 'IVA8CanibalFilip', 'IVA8CoufalovaJudita', 'IVA8DvorskyMichal', 'IVA8GeprtovaMartina', 'IVA8HalasVaclav', 'IVA8JuraMarek', 'IVA8KaresVit', 'IVA8KlimcakovaAnna', 'IVA8KoupilFlorian', 'IVA8KovarikVojtech', 'IVA8KurfurstAdam', 'IVA8LosseovaMarie', 'IVA8MohaplTomas', 'IVA8NavratilovaAmelie', 'IVA8NiemiecJiri', 'IVA8PippalNikolas', 'IVA8PospisilovaAnezka', 'IVA8ProchazkaJosef', 'IVA8ProchazkovaAnezka', 'IVA8PuskasJSamuel', 'IVA8SrotovaLucie', 'IVA8VanekKarel', 'IVA8VortelJakub', 'IVA8ZimovaSKarolina', 'IVB4BalnerovaAmalie', 'IVB4BenesKrystof', 'IVB4CharvatPetr', 'IVB4CtvrtlikovaElen', 'IVB4DrozdovaSvetlana', 'IVB4GalnorovaKaterina', 'IVB4HladisovaMarketa', 'IVB4JanosovaViktorie', 'IVB4KaiserovaAdela', 'IVB4KazinotaVojtěch', 'IVB4KnotkovaKaterina', 'IVB4KovalovaNikola', 'IVB4KovarikovaKlara', 'IVB4LiskovaJohana', 'IVB4MachalaJan', 'IVB4MensikMatej', 'IVB4PeleshkoKristyna', 'IVB4PospisilovaTereza', 'IVB4ReznickovaTereza', 'IVB4SanakJaroslav', 'IVB4SkopalovaLucie', 'IVB4SmatanovaKlara', 'IVB4SpitMartin', 'IVB4StruharovaGabriela', 'IVB4SvobodovaAneta', 'IVB4VachalovaAneta', 'IVB4VavrovaVendula', 'IVB4WunschovaKlara', 'IVB6BednarovaLudmila', 'IVB6BinarovaAdela', 'IVB6BombreovaJana', 'IVB6BurianovaIvana', 'IVB6CharvatovaKlara', 'IVB6DitmarovaValerie', 'IVB6DubovaTerezie', 'IVB6FinkovaVendula', 'IVB6ForalovaKaterina', 'IVB6GosovaEster', 'IVB6HartmannovaAlzbeta', 'IVB6HlaviznovaTereza', 'IVB6JuricekDavid', 'IVB6KlechPatrik', 'IVB6KosakovaEliska', 'IVB6KrumnikolvaEma', 'IVB6LosseJosef', 'IVB6NaspinskyDavid', 'IVB6NepsinskyDavid', 'IVB6SkopalovaAdela', 'IVB6SlotaVojtech', 'IVB6StancovaKamila', 'IVB6StastnaKarolina', 'IVB6StrnadovaKamila', 'IVB6UtikalovaLValentyna', 'IVB6VolmutJakub', 'IVB6VymazalTomas', 'IVB6ZaludaKrystof', 'IVB6ZamecnikovaElen', 'IVB6ZborilovaPavla', 'IVC4ApplHynek', 'IVC4DohnalJan', 'IVC4HatalovaMarketa', 'IVC4HenklovaEliska', 'IVC4KaplovaKarolina', 'IVC4LustigovaSophia', 'IVC4PodivinskyAdam', 'IVC4PrichystalKarlos', 'IVC4PrichystalovaMartina', 'IVC4PrincovaElizabeth', 'IVC4PsotkaVojtech', 'IVC4SandorJaromir', 'IVC4SanovecAdam', 'IVC4SpurnaEliska', 'IVC4StanoLukas', 'IVC4TajovskaKaterina', 'IVC4UtikalovaKarolina', 'IVC4VaculaAdam', 'IVC4VeselskaAnna', 'IVC4VykopalPavel', 'IVC4VysoudilovaVendula', 'IVC4ZdarilJakub', 'IVC4ZinkovaAneta', 'JanickovaAjCj', 'JonesAj', 'JurikTvZ', 'KalandrovaCjOv', 'KnapekAjSp', 'KonecnaNeCj', 'KostkovaMaCh', 'KovarovaMaCh', 'KralovaAj', 'KrcovaMaZ', 'KrejcirovaSp', 'KrejcirTvZ', 'KrizovaMaFy', 'KvapilMaFyHv', 'LekesovaCjHv', 'LetakovaBiCh', 'MadrovaAj', 'MarkovaBiCh', 'MartinikovaNeHv', 'MasnyOvVv', 'McMullinAj', 'MenouskovaCjFr', 'MinarikMa', 'NavratilBiZ', 'NavratilovaAj', 'NezvalovaAjRuD', 'OndrakOvLat', 'PazderovaMaFy', 'PetrMaFy', 'PiechovaAj', 'PohanelMaZAjProjekty', 'PolednovaMaZ', 'PridalovaAjRu', 'PrzybylovaCjHv', 'PuskarovaNeCj', 'RehulkaBiCh', 'RichterkovaMaFy', 'SedlackovaCjFr', 'SeverovaMaIVT', 'SladecekCjAj', 'SoubustovaNeRu', 'StanecSp', 'StepanovIVT', 'StranskaFy', 'StudnickaMaIVT', 'SuchankovaAj', 'SykorovaAjD', 'TeplyAjTv', 'UrbaskovaMaZ', 'VA6AujeskaKaterina', 'VA6CernoskovaLinda', 'VA6ChudzikJan', 'VA6DolezelovaAndrea', 'VA6GrablPatrik', 'VA6GunkovaEliska', 'VA6HarastovaEliska', 'VA6HautlerovaEliska', 'VA6KralovaSara', 'VA6KrejciMagdalena', 'VA6KrupickovaKamila', 'VA6LejskovaAdina', 'VA6MrazkovaAdela', 'VA6NavratilPetr', 'VA6OpletalovaSElisa', 'VA6PalouskovaTereza', 'VA6PavlickovaATerezie', 'VA6PavlickovaMonika', 'VA6PepekPospisil', 'VA6PolasekMartin', 'VA6PtasnikSimon', 'VA6PuckovaOlga', 'VA6RoubalikOta', 'VA6ValouskkovaMiroslavav', 'VA6VasickovaVendula', 'VA6ZakovaAnna', 'VA6ZavodnikovaBerenika', 'VA8BrundaAlbert', 'VA8DudovaAnezka', 'VA8DvorakovaVera', 'VA8GorcaRafael', 'VA8HavrlantovaElen', 'VA8HockadayMHana', 'VA8HrosovaMartina', 'VA8HudcovaNatalie', 'VA8JirovskyTomas', 'VA8JuklAlexander', 'VA8KalitaTomas', 'VA8KrobotAdam', 'VA8LemakovaHelena', 'VA8OndrejProkop', 'VA8PelclVojtech', 'VA8PracharSebastian', 'VA8ProchazkaJonas', 'VA8ProchazkaSimon', 'VA8ProchazkovaMKlara', 'VA8SolcMichal', 'VA8StolinFilip', 'VA8SvobodovaMartina', 'VA8VacekOliver', 'VA8VohralikJonas', 'VackovaCjVVEkonomie', 'VasiljevovaBiVV', 'VavraCjVV', 'VB6BurgetovaLucie', 'VB6HerynkovaEma', 'VB6HodgkinsDaniel', 'VB6HomolaVilem', 'VB6HosekFilip', 'VB6HrabalovaBarbora', 'VB6JuranovaEliska', 'VB6KestlKrystof', 'VB6KolarVojtech', 'VB6LachovaEvelina', 'VB6MacourkovaTereza', 'VB6MokrosovaKarolina', 'VB6NovakovaTereza', 'VB6PavkaRostislav', 'VB6PavlikovaMarika', 'VB6PerinaAdam', 'VB6PhungKienGiang', 'VB6PospisilovaDenisa', 'VB6PovysilovaAdela', 'VB6PracharovaKlara', 'VB6SajfrtovaKaterina', 'VB6SiotovaKlara', 'VB6StefankovaBarbora', 'VB6StoppenMatej', 'VB6SzromkovaKlara', 'VB6VyhnalkovaNella', 'VB6ZapletalovaMarketa', 'VB6ZapletalovaSimona', 'VB6ZarovskyVit', 'VB6ZdrazilMarek', 'VB6ZdrazilovaNela', 'VB8AlfamovaJulija', 'VB8ArabcukDavid', 'VB8CechacekAdam', 'VB8DobiasovaSara', 'VB8DolezalovaAnna', 'VB8FlajsarJan', 'VB8HolecovaAnna', 'VB8HorakovaBarbora', 'VB8KaderkaAlfred', 'VB8KauerovaKarolina', 'VB8KaureovaKaterina', 'VB8KovarovaKaterina', 'VB8KrestynovaMichaela', 'VB8LlunuskyMax', 'VB8MitrengaMatyas', 'VB8NezvalTadeas', 'VB8NohejlovaKaterina', 'VB8NovakovaEliska', 'VB8PucekMartin', 'VB8SlachtovaAdela', 'VB8SlajsovaLeona', 'VB8SolleRadovan', 'VB8StefanuttovaKlara', 'VB8StepanekJakub', 'VB8UrbanovaMonika', 'VB8UvirovaAlzbeta', 'VB8VyroubalovaEliska', 'VB8ZajcevDmitrij', 'VB8ZemanAntonin', 'VB8ZochvovaTereza', 'VeselaCjNe', 'VIA6BahounkovaTereza', 'VIA6BizovaLucie', 'VIA6BreznickyAntonin', 'VIA6CiseckaSandra', 'VIA6DrtikSimon', 'VIA6FibigrJiri', 'VIA6ForetkovaZElizabeth', 'VIA6HladikVaclav', 'VIA6HlousekPetr', 'VIA6HoncikovaNatalie', 'VIA6KnichalOndrej', 'VIA6KubickovaEva', 'VIA6KurfurstDavid', 'VIA6LosovaAneta', 'VIA6PalascakovaMarika', 'VIA6PavelkaTomas', 'VIA6PrikopovaEliska', 'VIA6SkrachovaViktorie', 'VIA6SoldanMichal', 'VIA6TalafousovaHelena', 'VIA6ValkovMarketa', 'VIA6VokalJonas', 'VIA6VolmutFilip', 'VIA6ZalioMarketa', 'VIA6ZatloukalovaMarie', 'VIA6ZdrazilCyril', 'VIA8BednarStepan', 'VIA8CoufalovaAgata', 'VIA8DejlovaKristyna', 'VIA8DufkaVojtech', 'VIA8GregurkovaNikola', 'VIA8HamrikovaVeronika', 'VIA8KardasPavel', 'VIA8KazimirKristian', 'VIA8KoisPavel', 'VIA8KolarikJaromir', 'VIA8KolarJan', 'VIA8KutinovaLucie', 'VIA8KvapilovaJana', 'VIA8MartiseekJiri', 'VIA8MikulkaPavel', 'VIA8NemravaJonas', 'VIA8NevrlaKristyna', 'VIA8OndrousekJakub', 'VIA8PodivinskyTomas', 'VIA8SchillerDenis', 'VIA8SiedloczekSebestian', 'VIA8SimacekSAdam', 'VIA8StavelovaBeata', 'VIA8SuchanekAdam', 'VIA8TomankovaKristyna', 'VIA8VecerovaNikola', 'VIA8VodickovaAdela', 'VIB6BacikovaAdela', 'VIB6BudikJiri', 'VIB6CaskovaAlena', 'VIB6CtvrtlikovaKlara', 'VIB6DitmarovaGabriela', 'VIB6EliasovaJana', 'VIB6GadburkovaKlara', 'VIB6HamplJan', 'VIB6HavranovaTerezie', 'VIB6HrabalikovaKaterina', 'VIB6HrbacMichal', 'VIB6JelinkovaMagda', 'VIB6KamidinovAdriania', 'VIB6KolarovaAnna', 'VIB6KrusoftovaAnna', 'VIB6MarackovaMichaela', 'VIB6MartinVelky', 'VIB6MerhautovaAlena', 'VIB6NejeschlebaMatej', 'VIB6PrchalovaTereza', 'VIB6SewaltTimothy', 'VIB6SiskovaKlara', 'VIB6SiskovaTereza', 'VIB6SkolovaKlara', 'VIB6SmatlakovaAnna', 'VIB6SvobodovaBarbora', 'VIB6VeceraOndrej', 'VIIA8AmbruzovaKlara', 'VIIA8CoufalovaAnezka', 'VIIA8CoufalovaMarta', 'VIIA8DolezalAlex', 'VIIA8HaichlovaAneta', 'VIIA8HermanPatrik', 'VIIA8JakubcovaAnna', 'VIIA8KlaskovaVanessa', 'VIIA8KlimovaNela', 'VIIA8KoudelkovaAnna', 'VIIA8KrylovaKristyna', 'VIIA8LexaMartin', 'VIIA8MilieDominik', 'VIIA8PeteraJaroslav', 'VIIA8PlodkovaZuzana', 'VIIA8PluskalVojtech', 'VIIA8PriborskyPetr', 'VIIA8ProchazkaJosef', 'VIIA8RudorferMartin', 'VIIA8SalekMarek', 'VIIA8SarazinPJulien', 'VIIA8SikorovaAneta', 'VIIA8SkacelOndrej', 'VIIA8SmidovaKlara', 'VIIA8StekldyMartin', 'VIIIA8BalusJan', 'VIIIA8BerankuViki', 'VIIIA8BieleszovaMarie', 'VIIIA8BlechovaAnna', 'VIIIA8BredburovaPavla', 'VIIIA8BrundaMatej', 'VIIIA8DolezalovaLucie', 'VIIIA8FikaZdenek', 'VIIIA8FilipcikStepan', 'VIIIA8FilkovaVendula', 'VIIIA8GrohmannOndrej', 'VIIIA8HamrikVit', 'VIIIA8HrabalMatej', 'VIIIA8JuraskovaTereza', 'VIIIA8KolarovaJudita', 'VIIIA8KratochvilMartin', 'VIIIA8KvapilJiri', 'VIIIA8MachacekMarek', 'VIIIA8MachacovaMonika', 'VIIIA8MarkovaMichaela', 'VIIIA8PanakovaLeona', 'VIIIA8PelakMatej', 'VIIIA8RatajovaVendula', 'VIIIA8StankovaSandra', 'VIIIA8SzaboVeronika', 'VIIIA8UngrovaStepanka', 'VIIIA8ZochovaBarbora', 'VitamvasovaAj', 'VojtovicovaMaFyAj', 'ZabojovaBiCh', 'ZajicovaCjNe', 'ZarubovaMaCh', 'ZatloukalovaVVRu']









print("pictures loaded")
print(time.time() - Start)

# for a in range(10):
#     print("trying", a)
#     video_capture = cv2.VideoCapture(a, cv2.CAP_DSHOW)
#     reat, frame = video_capture.read()
#     print(ret)
#     if ret == True:
#         break
#     else:
#         video_capture.release()
video_capture = cv2.VideoCapture(camera, cv2.CAP_DSHOW)
video_capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
video_capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)
# video_capture = cv2.VideoCapture(0, cv2.CAP_DSHOW)




print("video captured")
# print(video_capture)
# Initialize some variables
multipl = 1
resize = 1 / multipl
face_locations = [] 
face_encodings = []
face_names = []
process_this_frame = True
print("variables")
loop_noob = 0
while True:
    loop_noob = loop_noob + 1
    # Grab a single frame of video
    ret, frame = video_capture.read()
    if "None" in str(frame):
        print("dont have frame, skiping it")
        continue
    # frame = cv2.resize(frame, (960, 540))
    print(ret, loop_noob)

    # Resize frame of video to 1/4 size for faster face recognition processing
    # small_frame = cv2.resize(frame, (0, 0), fx=0.5, fy=0.5)
    small_frame = cv2.resize(frame, (0, 0), fx=resize, fy=resize)
    # small_frame = frame

    # Convert the image from BGR color (which OpenCV uses) to RGB color (which face_recognition uses)
    rgb_small_frame = small_frame[:, :, ::-1]

    # Only process every other frame of video to save time
    if process_this_frame:
        # Find all the faces and face encodings in the current frame of video
        face_locations = face_recognition.face_locations(rgb_small_frame)
        print("debuging is fun")
        face_encodings = face_recognition.face_encodings(rgb_small_frame, face_locations)

        face_names = []
        for face_encoding in face_encodings:
            # See if the face is a match for the known face(s)
            matches = face_recognition.compare_faces(known_face_encodings, face_encoding)
            name = "Unknown"

            # # If a match was found in known_face_encodings, just use the first one.
            # if True in matches:
            #     first_match_index = matches.index(True)
            #     name = known_face_names[first_match_index]

            # Or instead, use the known face with the smallest distance to the new face
            face_distances = face_recognition.face_distance(known_face_encodings, face_encoding)
            best_match_index = np.argmin(face_distances)
            if matches[best_match_index]:
                name = known_face_names[best_match_index]

            face_names.append(name)

    # process_this_frame = not process_this_frame


    # Display the results
    # print("tum")
    for (top, right, bottom, left), name in zip(face_locations, face_names):
        # Scale back up face locations since the frame we detected in was scaled to 1/4 size
        # top *= 4
        # right *= 4
        # bottom *= 4
        # left *= 4
        top *= multipl
        right *= multipl
        bottom *= multipl
        left *= multipl

        # Draw a box around the face
        cv2.rectangle(frame, (left, top), (right, bottom), (255, 0, 0), 2)

        # Draw a label with a name below the face
        cv2.rectangle(frame, (left, bottom - 35), (right, bottom), (255, 0, 0), cv2.FILLED)
        font = cv2.FONT_HERSHEY_DUPLEX
        cv2.putText(frame, name, (left + 6, bottom - 6), font, 0.5, (255, 255, 255 ), 1)

    # Display the resulting image
    cv2.imshow('Video', frame)
    # time.sleep(0.1)

    # Hit 'q' on the keyboard to quit!
    if cv2.waitKey(1) & 0xFF == ord('q'):
        # print("there")
        break
video_capture.release()
cv2.destroyAllWindows()

# Release handle to the webcam
 